### ISSUE TITLE
Support for Contenteditable

### ISSUE THREAD

**Issue by geertbrit** [mikeric/rivets#125]
I want to combine Rivets.js with something like Hallo.js to create an editor based on Contenteditable. 

After some research it doesn't seem enough to create a custom binding as suggested by @mikeric here: http://stackoverflow.com/questions/12302131/rivets-js-and-contenteditable

That's because the code directly goes to the adapter.publish instead of the proper (?) binding.publish, resulting in things as view-to-model formatters (https://github.com/mikeric/rivets/pull/90) not being called. 

Perhaps a better way (please keep in mind my knowledge with Rivets is 1 day old) would be to adapt the 'getInputValue'-funciton in Rivets to check for Contenteditable?

**Comment by erdalkaraca** [comment]
@terrancesnyder Tried your solution, but does not seem to work: the binder function is never executed (breakpoint not hit when in debugger), though the binder seems to be available when having a look at the rivets.binders array.
Should it work with the latest rivets version?

**Comment by jccazeaux** [comment]
Here is a full example : https://jsfiddle.net/jccazeaux/be2meL8g/
