### ISSUE TITLE
Computed property based on iterated objects properties

### ISSUE THREAD

**Issue by santervo** [mikeric/rivets#140]
Is it possible to refresh a computed property that is based on properties of array of objects.

For example here I have a function todoList:allChecked which returns true if all todo items are completed.
```
<input type="checkbox" id="toggle-all" data-checked="todoList:allChecked"/>
<ul>
  <li data-each-todo="todoList.todos">
    <input type="checkbox" data-checked="todo.completed"/>
    <span data-text="todo.title"></span>
  </li>
</ul>
```

Is it possible to have allChecked refresh when any of todo.completed changes? Or does someone have good idea how it could be implemented.

**Comment by Leeds-eBooks** [comment]
@santervo can this be closed? We're trying to tidy up the issues so we can focus on bugs and missing features.

**Comment by santervo** [comment]
@Leeds-eBooks yup, closing
