### ISSUE TITLE
What is the proper way to concatenate two fields together?

### ISSUE THREAD

**Issue by davidcl64** [mikeric/rivets#155]
I couldn't figure out if there was a syntax to join two fields together.  

For now, I was able to get it working using a custom binder as I can access the model from 'this' .  That doesn't feel right to me though.  

It looks like this:

```
rivets.binders.address1_2 = function(el, value) {
    var address1 = this.model.get('address1');
    var address2 = this.model.get('address2');

    $(el).text((address1 || '') + (address2 ? ', ' + address2 : ''));
};
```

Within the formatter call, there is no context (this === null).

Is there a better way to do this?

Ideally, I'd be able to specify the two fields in the binder attribute and rivets would register for changes to either field.  

BTW: great library!  I love seeing all the progress you've been making since I began following the project.

**Comment by jtrutwin** [comment]
I found this issue when googling for how to join / concatenate multiple fields in rivets.  I'm pretty new to rivets so I'm not sure I follow where exactly to put this function - I tried this:

```javascript
var eventData = {
   events: [ ],  /* filled in with an XHR request */
   rvFullDate: function() {
      console.log("hi!");
      var year = this.get('year');
      var month = this.get('month ');
      var day = this.get('day_of_month');
      return month + '/' + day + '/' + year;
   }
};
```

And I'm trying to use this in an rv-each:

```html
<tr rv-even-event="data.events">
   <td rv-text="event:rvFullDate < event.month event.day_of_month < event.year"></td>
</tr>
```

It doesn't seem to be working though, I don't even get the console.log("hi!") indicating it called the function.  Any ideas?  In the meantime I used 3 span tags, one for each field, but that seems ugly.

Thanks, really enjoying this library so far,

Josh
