### ISSUE TITLE
Add flag to skip specific nodes

### ISSUE THREAD

**Issue by jhnns** [mikeric/rivets#174]
I'm building an application that has nested views, for instance:

HomePage

``` html
<div>
    <h2 data-text="view.title"></h2>
    <div data-node="profile"></div>
</div>
```

And at `node="profile"` this view gets injected:

ProfileView

``` html
<div>
    <h3 data-text="user.name"></h3>
</div>
```

These examples have been simplified of course :wink:. Both views intiailize their dom parts with rivets. Is there a way to tell rivets to skip everything under `<div data-node="profile"></div>`? Because currently the bindings of ProfileView are applied twice.

**Comment by russplaysguitar** [comment]
:+1:
