### ISSUE TITLE
Feature - pass dependencies of computed property as arguments

### ISSUE THREAD

**Issue by davidcl64** [mikeric/rivets#175]
Say you have a form with several input fields.  The fields can have an error state associated with them, but only after an attempt has been made to save the form.

ie: when user submits form and field is empty,  outline the input element in red.

This can be accomplished with the current implementation but a computed property would have to be created for each field.

It would be much simpler, less code and reduce the functions dependency on the associated model(s) if the dependencies were passed so they could be used to calculated the computed value directly without accessing the model:

**Comment by Leeds-eBooks** [comment]
I'm going to close this because this can be achieved with formatters. The above example would be something like:

```
rv-class-errorstate="state.saving < model.firstname | checkFirstname model.firstname"

function checkFirstname(saving, firstname) {
  return saving && !isValid(firstname)
}
```
