### ISSUE TITLE
Accessing the view within a formatter

### ISSUE THREAD

**Issue by jhnns** [mikeric/rivets#187]
I've tried to write a formatter like this:

```html
<a data-on-click="view:doSomething | bind view"></a>
```

I know that the event handler's context is configurable, but sometimes you need to define the context just for a specific binding. In this case it would be great to have access to the view within the formatter so I could do:

```javascript
function bind(fn, context) {
    return fn.bind(this.models[context]);
}
```

There's another issue that surprised me: In my situation `view` provided a `bind`-method which was called instead of the `bind`-formatter. Renaming the formatter solved the problem. Is this behavior intended?

**Comment by Leeds-eBooks** [comment]
Closing this because as I understand it, this issue can be solved by passing arguments to formatters, which is now possible.
