### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by CalebGilbert** [mikeric/rivets#202]
Hi,

Rivets.js looks really interesting, however <a href="https://github.com/mikeric/rivets/wiki/Examples">neither example</a> seems to work in Chrome at the moment ("Rivets.js + Watch.js demo" does work in Firefox). 

Thought someone would/might like to know. :)

Kind regards,
Caleb

**Comment by Leeds-eBooks** [comment]
Closing as no longer the case
