### ISSUE TITLE
Broken 'value' binder in ie8/ie9 when jquery is unavailable

### ISSUE THREAD

**Issue by kastigar** [mikeric/rivets#212]
Here is requirements:
1. jQuery is unavailable
2. Browser is IE 8-9 versions (it is fine for IE10, don't know about IE7)
3. There is 'value' binder:
```html
<input type="text" data-rv-value="model.name" />
```
4. Value for input was chosen in suggestion box (so input was focused, some letters was typed, then suggestion box appears and value was chosen there, then blur)

When value was changed this way, publish will not be called (because `change` event will not be fired on input).
As i understand jQuery has workaround for `change` event in IE, but rivets.js hasn't. So 2-way binding is broken.

P.S. Suggestion box is internal IE feature, not third party plugin!

**Comment by wardtwits** [comment]
Same problem here.... Why is there no comments or fix for this issue?

**Comment by Duder-onomy** [comment]
The value binder in rivets works off of listening to the `input` event on the element bound with the value binder.
You can see from the source code that it listens for the `input` event.
https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L69

The input event is not supported in ie 8. 
https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/oninput

I do not know why it is not working in ie 9. That would take some debugging.

To get around this issue, I suggest manually firing the `input` event on any input when the input is blurred.
Something like:

```javascript
document.body.addEventListener('blur', function(event) {
    var inputEvent;
    if(event.currentTarget.nodeName === 'INPUT') {
        inputEvent = document.createEvent('HTMLEvents');

        inputEvent.initEvent('input', true, true);
        
        event.currentTarget.dispatchEvent(inputEvent);
    }
}, true);
``` 

I have not tested this, and I am not sure if that is how you create an event in ie 8. But this should get you started. 

This all being said, I do not know if rivets works in older ie at all, and I would be super interested to see. 

If you have a moment, can you download the repo and run the tests in ie 8 and 9? I do not currently have windows installed. 

I hope this helps.

**Comment by wardtwits** [comment]
Thanks.  "createEvent" isn't supported in IE8 although there are ways around that as well.
I might just go the simple route and do something like this:

```javascript
$(document).ready(function() {
    if ($('html').hasClass('ie8') || $('html').hasClass('ie9')) {
        $(document).on('keyup', 'input, textarea', function() {
            $(this).trigger('input');
        });
    }
});
```

**Comment by Leeds-eBooks** [comment]
Closing as it can be fixed by supplying a custom value binder (and this is a rare enough case these days that it probably doesn't need to be in rivets default binders).
