### ISSUE TITLE
Delayed value on inputs

### ISSUE THREAD

**Issue by contra** [mikeric/rivets#24]
It would be nice if you could specify when you want 'value' to be updated (keyup, keydown, keypress, etc.) to make everything look a bit snappier. Right now you need to lose focus/press enter before it will publish using data-value. I tried to accomplish this with an extension but modifying value within the context of the function has no effect. This might be a different issue but it would be nice to have control over changing the value from within an extension via some convenience functions.

What I want to do (rough example):

```coffeescript
rivets.register 'keyup', (el, val) ->
  el.addEventListener 'keyup', (e) -> 
    val += String.fromCharCode e.which
```

**Comment by gooftroop** [comment]
Having an issue with autocomplete as well - any update on this?

**Comment by Duder-onomy** [comment]
In the latest rivets 0.8.1.

The three binders that publish, where `published : true` in the binder listen as follows:

The `rv-checked` / `rv-unchecked` binders listen for 'change' https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L37

The `rv-value` binder listens for the 'input' event on input elements, and the 'change' event on radio inputs.
https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L75

@gooftroop Can you describe your issue in more detail? Is the input event not triggering autocomplete?

**Comment by Bluejay47** [comment]
I am bit confused as to how to apply formatters for form fields if you can't control when the timing on the binding.

For instance, I have a simple formatter that correctly formats a date in a text input field when the form appears.

rivets.formatters.datetime = {
    read: function (value) {
        if (moment(value).isValid()) {
            return moment(value).format('MM/DD/YYYY hh:mm A')
        } else {
            return value;
        }
    }
}

Everytime a character is changed its attempting to format the result as a date making it impossible to actually edit the value (you get garbled results since its formatting partial entries). It seems to me that the formatter should only attempt to format the field when the user finishes editing the value (lost focus)?

Some guidance would be appreciated. It seems that I do not understand how these formatters should be applied with the way the binder works.

**Comment by Duder-onomy** [comment]
@Bluejay47 Here is a `value-on-blur` binder:

```javascript
rivets.binders['value-on-blur'] = {
    publishes: true,
    priority: 2000,
    bind: function(el) {
        this.event = 'blur';
        rivets._.Util.bindEvent(el, this.event, this.publish);
    },
    unbind : function() {
        rivets.binders.value.unbind.apply(this, arguments);
    },
    routine : function() {
        rivets.binders.value.routine.apply(this, arguments);
    }
}
```

You can use it like: 

```html
<input rv-value-on-blur='model.something'/>
```

This will only run the binders routine when the input has been blurred. The formatters will run after that. 

Here is an example, from https://github.com/mikeric/rivets/issues/473 that demonstrates your issue exactly. Notice that the 'formatterThatMakesTextCamelCase' only runs once the input has been blurred.

As far as guidance goes, (my opinions)
It seems to me that the best way to go is get used to writing your own binders and formatters, when the originals don't de EXACTLY what you need, feel free to make new ones.  Don't be afraid to extend the functionality of the default ones. Rivets source does this quite often, in the case of the [`rv-unless` binder](https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L149) and the `{ }` interpolation.   I highly recommend spending some time reading rivets source code. The coffee script makes it difficult to understand, but in general it is very good. I have not used the components feature very much, but with custom adapters, binders, and formatters I have found I can get pretty damn far with no other dependencies.

**Comment by gooftroop** [comment]
@Duder-onomy Currently seeing the this issue on FF 34 CentOS 6 (my other devs are using newer browsers and have not seen this issue, but I don't think anyones tested for it yet). Updating my previous comment too as well - the dev sees this on a page refresh and not an autocomplete action on an input. I believe in FF this is also consider an autocomplete event (suggested fix is autocomplete=off) and strikes me as a race issue between the values being placed in the input box and rivets binding. I'm wondering if there has been any discussion on retroactively publishing data if said data existed when bound?

**Comment by Leeds-eBooks** [comment]
Closing this for now as it seems to have been resolved as far as possible. Custom binders are the way to go.
