### ISSUE TITLE
Assignment from withing the templates using '=', and disposable values.

### ISSUE THREAD

**Issue by MrSwitch** [mikeric/rivets#244]
Is it possible to assign a model value from within the template?

I want a sequence of clickable tabs (i've created an example of the affect i want to achieve e.g. http://jsfiddle.net/mr_switch/GueqA/)

However it would be great if one could assign the tab ID (e.g. 'a') to `view.selected` property in just the markup. aka...

     <li rv-on-click="data.selected = 'a'" rv-class-open="data.selected | eq a">List item one</li>

..., Nor have to define `data.selected` in the model - as it's purely UI sugar. This alas seems impossible to do at the moment.

Thanks (Great project!)
A

**Comment by Leeds-eBooks** [comment]
Closing as I don't think this kind of logic should be in the view templates – it should be in methods on the viewModel.
