### ISSUE TITLE
Change of Input value is not refelected when modification is done by third party code

### ISSUE THREAD

**Issue by nsisodiya** [mikeric/rivets#249]
Here is a demo - 

http://jsfiddle.net/nsisodiya/jzYj4/

If you type anything in input box, it will be reflected back in model !

but if I modify the value of input element using JavaScript then the value is not reflected back in model , ie model is not updating.

I know, If I type
```
scope.price = parseInt(scope.price) + 10;
```
then everything will work because I am directly modify the model !
But in actual code, My third party decorator plugin do not know about model, so what should i do in such kind of situation !

**Comment by Leeds-eBooks** [comment]
Closing this as it's not in the scope of rivets to handle 3rd-party code by default. This could be addressed with a custom binder.
