### ISSUE TITLE
Passing rivets instance to formatters and adapters

### ISSUE THREAD

**Issue by MiguelCastillo** [mikeric/rivets#254]
I am running into a situation where I really need access to the rivets instance so that I can access the dom element being processed.  I have manually changed rivets to pass "this" when calling the adapter.subscribe interfaces.

So, what I am doing is that I am actually storing information in the element that I access when I get event callbacks for things like clicks.

Thanks!
-Miguel

**Comment by Leeds-eBooks** [comment]
Closing this for the reasons @jhnns states above
