### ISSUE TITLE
The `rv-each-*` binder stops functioning after unbind()

### ISSUE THREAD

**Issue by amireh** [mikeric/rivets#261]
Hi. I'm coming across a really confusing issue when calling `View.unbind()` and then later on building another view using `rivets.bind()` on the _same_ element; everything is working except the `rv-each-*` blocks; the items are no longer bound.

I suspect that rivets is applying an irreversible modification to the DOM element that prevents it from correctly parsing/building it on successive `bind` calls.

The behavior is reproducible as can be seen in this [JSFiddle](http://jsfiddle.net/SfqAB/13/). It starts out with a dropdown of 3 currencies, a model that references a single currency (USD), and then another that references another (EUR) - all is working great. Yet once the view is unbound and another is bound to the same element, the dropdown `option[value]` are all empty!

The only workaround that I found is to never unbind the view... but that's not really nice, as the component could sit in the background for a long time and its bindings are needless then.

PS: thank you for the **awesome** library, I've been using rivets for three days now and it's really enjoyable (maybe except for the lack of documentation, but perhaps I can contribute once I get over the confusion!)

**Comment by Leeds-eBooks** [comment]
Closing as this appears to have been resolved
