### ISSUE TITLE
root element not goes via adapter

### ISSUE THREAD

**Issue by mogadanez** [mikeric/rivets#282]
using https://github.com/azproduction/rivets-backbone-adapter

```
<li rv-each="someCollection"></li>
```

```
rivets.bind( el, { someCollection:someCollection })
someCollection.add( new Item() )
```

nothing happens. collection not subscribed for changes

only way i was achieved  goal - make surrogate wrapper.
http://jsfiddle.net/v2YWk/8/

**Comment by Leeds-eBooks** [comment]
Closing as not an issue
