### ISSUE TITLE
rv-each-* and filtering, how?

### ISSUE THREAD

**Issue by hogart** [mikeric/rivets#313]
I need to dynamically filter my collection, i.e. render only a subset of Backbone collection when some checkbox is checked.

My view is:
```html
<div rv-each-device="devices | myFilter < overview:filter">
```

And my filter is:
```js
myFilter: function (value) {
    if (overview.get('filter')) {
        return value.filter(function (model) {
            return model.get('shouldBeVisibleOnFilter');
        });
    } else {
        return value.models;
    }
},
```

I hoped that `<` will cause recalculation of filter, but no. Am I doing something wrong?
I double checked that filter itself works as expected and `overview:filter` is changed correctly.

**Comment by Leeds-eBooks** [comment]
Closing as a solution was provided
