### ISSUE TITLE
builtin "dot" adapter seems to be executed unexpectedly

### ISSUE THREAD

**Issue by jokeyrhyme** [mikeric/rivets#314]
Hi. I'm been using Rivets for a while, and really appreciate the effort invested it in. Thanks for the great work. :)

I'm using the suggested Backbone Model adapter for compatibility with IE8 (I know, I know). So the object-property delimiter is `:`. I've put an example up here: http://jsfiddle.net/jokeyrhyme/A5m4N/

I do have a question about the built-in "dot" adapter. According to the above jsFiddle, the built-in `.` adapter is being executed even though my bindings only use the custom `:` adapter. Is there a reason for this? Do all adapters require the built-in adapter in some way?

I'm going to try to un-define the built-in adapter for my Backbone projects, mostly to try to increase compatibility with IE8 (/sigh). Do you think this is a good approach? Any hints as to the safest way to accomplish this?

Is it worth submitting a PR to only execute adapters when there is a binding that explicitly involves them?

Might be related to #295 ?

**Comment by Leeds-eBooks** [comment]
Closing as it is expected behaviour
