### ISSUE TITLE
Filtering data sets with computed properties

### ISSUE THREAD

**Issue by JoeAxon** [mikeric/rivets#317]
http://jsfiddle.net/j25W7/2/

I'm basically trying to filter a data set by a type column which can be changed using a select.

The issue is that the type change doesn't appear to propagate to the iterated data set.

The expected result is that when the select is changed the data set should change also.

I'm not sure if this is a bug or I'm just approaching it the wrong way!

Thanks

**Comment by Leeds-eBooks** [comment]
Closing as it is so old, @JoeAxon please let me know if this is still an issue
