### ISSUE TITLE
Don't update the input field that changed.

### ISSUE THREAD

**Issue by aristidesfl** [mikeric/rivets#326]
http://jsfiddle.net/gh3Zy/3/

In the example above, if you write the number 2 in the fahrenheit field, it gets replaced with 1,9999999999999964. After the model gets updated, it comes back to the DOM. Some libraries like Angular and Vue don't seem do this. It's unclear which behaviour is preferable, but personally I've been finding that not updating input fields which the user is changing generally creates less problems than doing so.

Same example with other libs: http://n12v.com/2-way-data-binding/

**Comment by Leeds-eBooks** [comment]
Closing as could be fixed with a custom binder
