### ISSUE TITLE
'rv-checked' not working with radio inputs

### ISSUE THREAD

**Issue by ilyashubin** [mikeric/rivets#334]
`rv-checked` binding works fine with checkboxes, but not with type='radio'. Can someone check this or is there some trick to make it work for radio type?
I'm using latest rivets.js version.

``` html
<input type="radio" rv-checked="opt.active" rv-name="opt.name"></input>
```

UPD: just realized that rv-checked on `input[type=radio]` converts boolean value in model to "on".
Am I misunderstood something or it's a bug?

**Comment by andras-sallai-planorama** [comment]
```
<li rv-each-color="view.colors">
  <input type="radio" rv-value="color" rv-checked="user.selectedColor">
</li>
```

This correctly injects the selected value in the UI, BUT the data won't be bound and I can't figure it out for the life of me...
We need rv-each and we also need the data to be two-way-bound to the model. How can we do that?

**Comment by Duder-onomy** [comment]
@andras-sallai-planorama [Here is a working jsfiddle](https://jsfiddle.net/yhy6w5z9/) similar to to the examples detailed above. 
It should demonstrate that the value is properly bound. If you change the selected radio, it will change the bound input. 

Can you make a jsfiddle, or give us some examples of your code to reproduce the issue you are having?

**Comment by andrewjw1995** [comment]
Hi Mikeric,
Could you please leave a note in the binder references about the checked binder referring to the value, and not a boolean, when bound to a radio? I would have expected it to be a boolean indicating whether the item is selected or not, I spent a long time trying to work out what I was doing wrong...

**Comment by Jmeyering** [comment]
Agreed, the documentation leads a user to believe that rivets sets the model value to a boolean rather than to the value of the radio.

**Comment by ksikka** [comment]
I second what @andrewjw1995 said. I just spent 10-20 minutes figuring this out by looking at the source code. Would be happy to submit a pull request if you're open to it, @mikeric

**Comment by Duder-onomy** [comment]
This is how radio inputs work normally in html. Do you think rivets should break this? https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

Or is it just a problem with the docs?

**Comment by ksikka** [comment]
Just a problem with the docs.

**Comment by AntoineInsa** [comment]
Hey! 
I actually run into a possible related issue, where rv-show and rv-hide don't follow the state of a radio-button (even though the text interpolation is). Here are more details https://jsfiddle.net/yhy6w5z9/6/
