### ISSUE TITLE
Print the line break in the html.

### ISSUE THREAD

**Issue by rafaeldruiz** [mikeric/rivets#338]
This is a stupid question, but how can I print the line break with rivets?

I have a simple html code (above), where scopeComments is retrieved from the database.

```
   <span id="currentScopeComments" class="showcase">
      {: model.scopeComments :}
   </span>     
```

The scopeComment has line breaks with "\n" and it is ok in the "Inspect Element" of Chrome:

```
<span id="currentScopeComments" class="showcase">
                                Test of ScopeComments

JKcjdsklcj dsl


jcsjlcdsjcdms.cdscsd


cdscds
</span>
```

The problem is that in the html it is in a single line.

Thanks for the help.
Rafael.

**Comment by PierBover** [comment]
This issue shouldn't be closed.

How can you pass a line break to Rivets?

I've tried passing `<br>`, `\n`,and even `\r`... but the text gets printed literally instead of being interpreted as a line break.

**Comment by Duder-onomy** [comment]
@PierBover here is a working fiddle demonstrating how to ensure a line break in rivets.
http://jsfiddle.net/gj7bssyp/

The important thing to note is that the `rv-text` and `{{ }}` binders will not do what you want. 
You need to use the `rv-html` binder.

Does that help?

**Comment by PierBover** [comment]
Thanks again @Duder-onomy! Very helpful as usual :)
