### ISSUE TITLE
animating transitions

### ISSUE THREAD

**Issue by FND** [mikeric/rivets#361]
As far as I can tell (though I'm still pretty inexperienced with Rivets), there's no straightforward way to animate transitions when the DOM changes. For example:

    <p rv-if="view.toggle">lorem ipsum</p>
    <p rv-unless="view.toggle">dolor sit amet</p>

    <ul>
        <li rv-each-item="view.items">{ item }</li>
    </ul>

Here I might like to slide up the first element and slide down the second when `toggle` changes (and vice versa).
Similarly, I'd want to fade in new `item`s and fade out deleted ones.

Are there any hooks I could use perhaps? (I've seen the discussion in #267, but I'm not sure that's quite the same.)

**Comment by psibernetic** [comment]
The approach I have taken is to keep my template and usage of templates separate. I then bind a new clone of my template and replace the old content.

    var el = $('#template').clone();
    rivets.bind(el, model);
    $('#container').fadeOut("slow", function(){
        $(this).replaceWith(el);
        $('#container').fadeIn("slow");
    });

**Comment by Leeds-eBooks** [comment]
This is an old question but I've just implemented this, so in case anyone also has this question, I did it with a simple binder as follows:
```js
  /**
  * Promisified CSS transition events
  * @param  {HTMLElement} el        The element to watch
  * @param  {String}      action    The `classList` method: "add", "remove" or "toggle"
  * @param  {String}      className The className to be added/removed
  * @return {Promise}               Resolves on `transitionend` event
  */
  var trans=function(el,action,className) {
    return new Promise(function(resolve) {
      function end() {
        el.removeEventListener("webkitTransitionEnd",end);
        resolve(el);
      }
      el.addEventListener("webkitTransitionEnd",end);
      el.classList[action](className);
    }).cancellable();
  };

  rivets.binders.reveal={
    bind: function(el) {
      el.style.display='none';
      this.revealClass=el.getAttribute('data-reveal-class');
    },
    routine: function(el, value) {
      var revealClass=this.revealClass;
      if (value) {
        el.style.display='';
        setTimeout(function() {
          el.classList.add(revealClass);
        }, 0);
      } else if (el.style.display!=='none') {
        trans(el,'remove',revealClass).then(function(el) {
          el.style.display='none';
        });
      }
    }
  };
```
```html
<div class="search-bar" data-reveal-class="unfade" rv-reveal="search">
  <!-- content -->
</div>
```
