### ISSUE TITLE
Observe any changes on object/model as a whole

### ISSUE THREAD

**Issue by peckomingo** [mikeric/rivets#372]
I am building a widget configuratior where the user can see how the widget  will appear on his/her blog and generate the embedcode. The user can customize  colors, sizes, textures etc. for the widget.
The configObject looks like this:

```javascript
settings: {
    numberEntries : 2,
    variant: 1,
    paperlook: true,
    dimensionX : 250,
    bgColor : "#F7F7F7",
    accentColor : "#9F9C8E",
    primaryTxtColor: "#433924"
 }
```

Every time a value changes the change gets reflected in the preview, this works fine and rivets is very cool for this purpose.
For reasons of control and debugging I want  to output the above configObject in a div.  So I want to subscribe to any changes in the **whole** model not just one particular property. Ever time **any*** value in settings changes a want to do something.

So I tried

```html
<div class="codeExport">
    {settings | showjson};
</div>
```

and

```javascript
rivets.formatters.showjson = function(value){
    return JSON.stringify(value);
};
```

But this just renders the JSON string on pageload and do not update on changes.

Any hints?

**Comment by kovalenko0** [comment]
I hope this will help somebody:
to observe changes of child `settings`child properties one can use Sightglass.js

**Comment by Leeds-eBooks** [comment]
Closing as the Sightglass solution offered by @kovalenko0 is the recommended behaviour

**Comment by jepek** [comment]
I'm not satisfied of this answer, because with Sightglass as I know you can observe only concrete properties. What if I would like to observe all properties in some object (in this case settings)? 

I'm able to do that with Watch.js (http://jsfiddle.net/C83pW/27/) but I would like to avoid setInterval coming from watch.js

**Comment by Duder-onomy** [comment]
@jepek Something like this can be done with `Object.observe` very nicely. 

Here is a [fiddle](https://jsfiddle.net/jr9d8dfc/).
I have made a debug adapter. You can put it on the end of any keypath so to force update on any change. 

The important parts: 

Create an adapter that will listen for any change to the subscribed object and call the callback when changed:
```javascript
rivets.adapters['*'] = {
    observe: function(obj, key, callback) {
        Object.observe(obj, callback);
    },
    unobserve: function(obj, key, callback) {
    },
    get: function(obj, key) {
        return obj;
    },
    set: function(obj, key, value) {
    }
};
```

Make a `toJson` formatter:
```javascript
rivets.formatters.toJson = function(value) {
    return value && JSON.stringify(value, null, 4);
}
```

Use it in your html:
```html
<pre rv-text='settings* | toJson'></pre>
```

Will this work for your use case?
