### ISSUE TITLE
Binding Attributes with Some Static Value

### ISSUE THREAD

**Issue by alanjames1987** [mikeric/rivets#387]
I want to be able to create an anchor tag inside of a `rv-each`. Here is the code that doesn't work.

``` html
<div rv-each-project="projects">
    <a href="/#/note/{project.id}">{project.id}</a>
    <p>{project.title}</p>
</div>
```

How do I go about binding an `href` like this?

**Comment by 84pennies** [comment]
I ended up making something a bit more flexible. It's a way to either combine multiple properties together or combine them into some string.  Here's how it looks in the markup:

```
<a rv-href="group.Id | text 'group.aspx?id=@0&name=@1&owner@2=' group.Name group.Owner">My Link</a>
```

When you use the formatter in the markup, you first pass the string you want to output. Then you pass any additional values you want to use in the string besides the initial value that's specified before "pipe" character.

In my example, the string replacement looks at:

@0 is the initial property "group.Id"
@1 is the "group.Name"
@2 is the "group.Owner"

The formatter will accept as many arguments as you want.

Here's the js to add this formatter to rivets (using a jQuery $.each)

```javascript
rivets.formatters.text = function (value, text) {
    text = text.replace('@0', value);

    var args = (arguments.length === 1 ? [arguments[0]] : Array.apply(null, arguments));
    args.shift(); args.shift(); //remove the first two arguments from the array
    
    $.each(args, function (i) {
        var replaceChar = '@' + (i + 1).toString();
        text = text.replace(replaceChar, this);
    });

    return text;
};

```

**Comment by kitsu** [comment]
Check out [Rivets StdLib](https://github.com/matthieuriolo/rivetsjs-stdlib/blob/03f36eb956aff342cc98e79a8fd334440449b3b2/src/rivetsstdlib.js#L351) for another implementation (easily converted to [TinyBind](https://github.com/blikblum/tinybind))
