### ISSUE TITLE
Ie8 support?

### ISSUE THREAD

**Issue by orneryd** [mikeric/rivets#397]
There is no polyfill for object.defineProperty. Is there a version that does support ie8?

We absolutely need to have ie8 support and rivets is the only viable databinding solution for backbone in a production environment. I would be happy to help fix this. We would all love to not support ie8 but the sad reality or corporate customers refuse to upgrade and demand support.

**Comment by Jmeyering** [comment]
@MiguelCastillo Any chance those files could be place somewhere else? I've been looking for this solution also.

**Comment by MiguelCastillo** [comment]
@Jmeyering I have been meaning to do that.  Let me see if I can do it sometime tomorrow. At the very least, I will put them on a small git repo.

**Comment by Jmeyering** [comment]
@MiguelCastillo Thanks so much!

**Comment by jepek** [comment]
@MiguelCastillo I can't find the repository with ie7 support. Did you create it?

**Comment by MiguelCastillo** [comment]
Hey folks, I am a bit embarrassed to say this but I don't have the files anymore...  @timothyswt any chance you saved those files?

I don't want to make promises because I am really struggling to find time, but if nobody else has the files I will try to find some time for this during the weekend.
