### ISSUE TITLE
select2 and version 0.7.1

### ISSUE THREAD

**Issue by dftoro** [mikeric/rivets#418]
Using select2 with rivets 0.6.10 (using on-blur) worked fine, but using version 0.7.1 (using on-change) isn't working: http://jsfiddle.net/ff6jourp/4/

The model value isn't setting.  
Any suggestion.

**Comment by dftoro** [comment]
Any idea to resolve this issue ?

Thanks

**Comment by dftoro** [comment]
jsfiddle updated:  http://jsfiddle.net/376s2864/55/

**Comment by Duder-onomy** [comment]
Here is your fiddle working: http://jsfiddle.net/jc07rk5m/
You can always write a special binder for your special case, since making an `input` tag be a `select` tag seems a bit odd.

The code in question: 

```html 
<input id="inSel2" type="hidden" rv-input-el-as-select-el="mod:inTest" />
```

```javascript
rivets.binders['input-el-as-select-el'] = {
    publishes: true,
    priority: 2000,
    bind: function(el) {
        this.event = 'change';
        rivets._.Util.bindEvent(el, this.event, this.publish);
    },
    unbind : function() {
        rivets.binders.value.unbind.apply(this, arguments);
    },
    routine : function() {
        rivets.binders.value.routine.apply(this, arguments);
    }
}
```

**Comment by dftoro** [comment]
It works fine. Thank you.
