### ISSUE TITLE
Second splice call on arrays fails with "TypeError: map is undefined" 

### ISSUE THREAD

**Issue by azeem** [mikeric/rivets#436]
I recently switched to 0.7.2 and when splicing arrays bound to rivet views i get "TypeError: map is undefined" exception.

Here is a jsfiddle that demonstrates the issue http://jsfiddle.net/652qtjdp/1/

**Comment by GianlucaGuarini** [comment]
I got the same issue here :(

**Comment by Leeds-eBooks** [comment]
I think this is related to https://github.com/mikeric/rivets/issues/441

**Comment by mikeric** [comment]
Thanks guys. This issue should be fixed in 0.8.0 (just reload that JSFiddle example above).
