### ISSUE TITLE
Binder for enter keypress

### ISSUE THREAD

**Issue by mciparelli** [mikeric/rivets#440]
This is not exactly an issue, but I couldn't find in the docs how to write a custom binder to fire on "enter keypress" for an input.
Can anyone introduce me on how to write such binder? Tried several examples following the docs with no luck.

**Comment by Duder-onomy** [comment]
With Jquery
```javascript
rivet.binders['on-enter-key-press'] : {
    bind : bindKeypress,
    unbind : unbindKeypress
}

function bindKeypress(el) {
    var rivetsView = this, $el = $(el);

    $el.on('keypress', function(event) {
        if(event.keyCode === 13) {
            $el.blur();
            rivetsView.view.models.view[rivetsView.keypath](event);
        }
    });
}

function unbindKeypress(el) {
    $(el).off('keypress');
}
```

You would use it like:
```javascript
var view = {
    handleEnterKeyPress : function(event) {
         // do stuff and junk.
    }
};

rivets.bind($('input'), { view : view });
```
```html
<input type='text', rv-on-enter-kepress='view.handleEnterKeyPress' />
```

Leme know if that helps. This would work on any element.

**Comment by mciparelli** [comment]
Thank you very much. Haven't tried it yet but it helps to see how I can access the model and keypath. I'll close as soon as I can confirm this works as expected

**Comment by mciparelli** [comment]
Tried that but `rivetsView.view.models.view` seems to be undefined. and `rivetsView.view.models[rivetsView.keypath]` won't work either because of the dot notation :/

**Comment by Duder-onomy** [comment]
Yeah, the `.view` corresponds to the ` { view : view }` passed to the binding.
So, if you were to put your handler on an object called `controller`, your code might look like this.

the binder definition: (notice that `rivetsView.view.models.view` is now `rivetsView.view.models.controller`)
```javascript
rivets.binders['on-enter-key-press'] : {
    bind : bindKeypress,
    unbind : unbindKeypress
}

function bindKeypress(el) {
    var rivetsView = this, $el = $(el);

    $el.on('keypress', function(event) {
        if(event.keyCode === 13) {
            $el.blur();
            rivetsView.view.models.controller[rivetsView.keypath](event);
        }
    });
}

function unbindKeypress(el) {
    $(el).off('keypress');
}
```

the code: 
```javascript
var controller = {
    handler : function() {}
};

rivets.bind(element, { controller : controller });
```
the html would be 
```html
<input type='text' rv-on-enter-key-press='controller.handler' />
```

Do you catch what I am throwing?

**Comment by mciparelli** [comment]
Oh I understand now. Thanks for the quick reply. So I'm tied to always use the same "namespace" if I want the binder to work, that's noisy. I mean if I use `controller.handler` I won't be able to use `view.handler` later, right?

**Comment by Duder-onomy** [comment]
Word, yeah, making a fiddle for you right now. Should clear stuff up.

**Comment by Duder-onomy** [comment]
anyhow, was looking at Sightglass, there is a `.value()` you can call on the `rivetsView.observer`.  This will return that method, so you can just call it like so:
`rivetsView.observer.value()(event)` This will save you from the 'controller / view' problem. 

Here is the fiddle: http://jsfiddle.net/wk3gLvod/2/

Also, because in the input, you are sending in the value `view.handleEnterKeyPress`, to prevent it from being called right off the bat, you need to provide the `function : true` option on your binding.

I will update the first comment so that if someone stumbles here they will see a complete example.

**Comment by mciparelli** [comment]
You've been of great help man, thanks. I'm gonna close this, although I guess the docs either here in the repo or in the webpage are outdated regarding this or for example how to get the current adapter among other stuff.
