### ISSUE TITLE
Cannot read property 'callbacks' of undefined in unobserve

### ISSUE THREAD

**Issue by ZAYEC77** [mikeric/rivets#441]
If was updated the values of the scope sereval times (maybe it happens when use "each-*")
Will be received error: `Cannot read property 'callbacks' of undefined`
[JSFilddle](http://jsfiddle.net/y3gDP/29/).
The error is in `unobserve` in  Rivets["public"].adapters['.']:
```js
//...
unobserve: function(obj, keypath, callback) {
      var callbacks, idx, map;
      map = this.weakmap[obj[this.id]];
      callbacks = map.callbacks[keypath];
      if ((idx = callbacks.indexOf(callback)) >= 0) {
        callbacks.splice(idx, 1);
        if (!callbacks.length) {
          delete map.callbacks[keypath];
        }
      }
      this.unobserveMutations(obj[keypath], obj[this.id], keypath);
      return this.cleanupWeakReference(map, obj[this.id]);
    },
//...
```
In come cases variable `map` is `undefined` and this is the cause of the error.
If checking are added error disappears

**Comment by Leeds-eBooks** [comment]
:+1: I've just started getting this error, don't know why or what's changed to make it happen.

**Comment by Leeds-eBooks** [comment]
Ok actually I did change something - I changed the array referenced by my `rv-each` attribute from an array of strings to an array of objects. I don't understand how the weakMap thing works, so I can't say if this would cause the issue - anyone else able to corroborate this?

**Comment by ZAYEC77** [comment]
I seen similar issues

**Comment by anton-suprunov** [comment]
Getting same issue here

**Comment by mikeric** [comment]
Thanks everyone. This issue should be fixed now in 0.8.0.

Updated your JSFiddle example here. http://jsfiddle.net/y3gDP/33/

**Comment by Leeds-eBooks** [comment]
Yes this is now fixed! Thanks very much for quick work on this. It only adds to the confidence I have in using rivets in production.

**Comment by slashhuang** [comment]
i got the same issue,hope 0.8.0 can solve this problem
