### ISSUE TITLE
"newi is not defined"

### ISSUE THREAD

**Issue by raysuelzer** [mikeric/rivets#444]
Hi,

I'm using the latested minified and bundled version but am getting a console error that "newi" is not defined.  Am I missing a dependency? 

Thanks!

**Comment by raysuelzer** [comment]
I must have deleted a space between new and i...

**Comment by hogart** [comment]
Seems that you have typo in your code. Anyway, console shows you filename
and line number of error location.
Bit of advice: do not use minified libraries in development, they are hard
to debug. You should only pack and minify scripts on production sites.
