### ISSUE TITLE
Accessing original data from iteration

### ISSUE THREAD

**Issue by Arjeno** [mikeric/rivets#449]
I'm unable to access the original data from within an iteration. Example:

```html
<div rv-each-article="articles" rv-class-active="article.id | eq currentArticle.id">{ article.title }</div>
```

`currentArticle` is not accessible within the iteration. Any help would be appreciated!

**Comment by Arjeno** [comment]
Actually, it works in a simple fiddle. I'll close this for now.

**Comment by Duder-onomy** [comment]
Word. Just finished this one for you: http://jsfiddle.net/wzr0afhL/.
Glad yours worked too.

**Comment by Arjeno** [comment]
Thanks again @Duder-onomy :)
