### ISSUE TITLE
Set existing input value from DOM when binding

### ISSUE THREAD

**Issue by DominicTobias** [mikeric/rivets#450]
I have a situation where I am not dealing with a single-page app and it is possible the server has already set a value on the input, e.g:

```<input type="text" value="a value" rv-value="model:something | someformatter">```

I would like to set "a value" on the model's "something" attribute, first passing it through a formatter if it was specified.

Do you know any way I could do this? Thanks

**Comment by Duder-onomy** [comment]
In the case of having both a value in the input, and a diff value on the property you are binding, which one wins when you call rivets.bind?

Demonstrating my question: http://jsfiddle.net/nfbz3pL9/2/

You can make your own value binder for this (the initial DOM state before binding wins)
Here is one that is working....pretty hacky if you ask me...but it does what you asked.  Notice that the input bound with `rv-value` and the input bound with `rv-value-soft` are in sync. http://jsfiddle.net/nfbz3pL9/37/

```javascript
rivets.binders['value-soft'] = {
    publishes : true,
    priority : 3000,
    initialized : false,
    bind : function(el) {
        rivets._.Util.bindEvent(el, 'input', this.publish);
    },
    unbind : function(el) {
        rivets._.Util.unBindEvent(el, 'input', this.publish);
    },
    routine : function(el, value) {
        if(el.value && !this.binder.initialized) {
            this.binder.initialized = true;
            this.publish();
            rivets.binders.value.routine(el, el.value);
        } else {
            rivets.binders.value.routine(el, value);
        }
    }
};
```

**Comment by DominicTobias** [comment]
Thanks a lot for taking the time to do that. Totally agree and it frustrates me coming on to a project which is both trying to be a clientside project with models and collections, and yet passing down fully formed html from the server with data already set in forms which are supposed to be represented by clientside models. Makes me puke a little. I will make some passive aggressive comments about the architecture tomorrow ;)

**Comment by Duder-onomy** [comment]
LOL yeah, I feel your pain. The current project I am on is a hybrid SPA. Most of the HTML is rendered on the server. The big issue I have found is with iteration. That I could bind to a pre-iterated element. 
I got around allot of the issues by swapping the pre-iterated content out after the newly iterated stuff is bound. Anyhow. Rivets is madd chill.

**Comment by DominicTobias** [comment]
We have made an uneasy truce where the server renders out the forms, but the initial data is described in a global object.. urg - still better than html parsing as I can just dump the data into collections or models before binding.

Off topic but do you have any idea why this isn't working: http://jsfiddle.net/ferahl/fwhuf/88/ - Would be much appreciated!
