### ISSUE TITLE
class-[classname] concatenation support

### ISSUE THREAD

**Issue by logeshpaul** [mikeric/rivets#451]
For a certain requirement I need to have dynamic class names.

What I'm expecting
`<i class="icon-"{ forecast.code }></i> `
[to] 
`<i class="icon-5"></i>`

How can I concatenate in attributes?

**Comment by hogart** [comment]
Simple binder would do the trick:
```html
<i rv-codeIcon="forecast.code"></i>
```
```js
codeicon: function (el, value) {
    el.className = 'icon-' + value;
}

**Comment by logeshpaul** [comment]
@hogart Thanks for snippet, will give it a try :+1:

**Comment by psibernetic** [comment]
Wouldn't the [attribute] binder with a formatter work as well?

     <i rv-class="forecast.code | iconPrefix"></i>

    rivets.formatters.iconPrefix = (val) {
        return 'icon-' + val
    }

**Comment by logeshpaul** [comment]
Binder does the job! 

Thanks @hogart & @psibernetic
