### ISSUE TITLE
When using rv-each, is it possible for events to be passed the current item?

### ISSUE THREAD

**Issue by atrauzzi** [mikeric/rivets#459]
I have the following markup:

		<li rv-each-entity="entity_search_data">
			<span
				rv-title="entity.description"
				rv-on-click="entitySelected"
			>{ entity.title }</span>
		</li>

However when `entitySelected` is called, I see that I get the event and the entire scope, but I'm not sure of any way to have it receive `entity` (as it's defined here).

**Comment by Duder-onomy** [comment]
It should be passed in as `scope.entity` 

For example: ( a working [jsfiddle](http://jsfiddle.net/tsqd1daw/4/) )

```javascript
var entity_search_data = [
    {
        description : 'John',
        title : 'Lennon'
    },
    {
        description : 'Paul',
        title : 'McCartney'
    },
    {
        description : 'Ringo',
        title : 'Star',
    },
    {
        description : 'George',
        title : 'Harrison'
    }
];

rivets.bind(document.getElementById('container'), { 
    entity_search_data : entity_search_data,
    entitySelected : function(event, scope) {
        console.log(scope.entity);
    }
});
```

**Comment by atrauzzi** [comment]
Oh good!  That might be worth adding to the docs as it wasn't immediately apparent to me.

Thanks!
