### ISSUE TITLE
rv-value with custom two-way formatters changes input text while user is typing

### ISSUE THREAD

**Issue by joostverdoorn** [mikeric/rivets#473]
Hey there,

I have an issue which I'm unsure how to solve neatly. I use a custom two-way formatter to format numbers in an input, which I've bound to my data source using `rv-value`. The problem is that on every `input`-event, the data is formatted by the formatters, set in my data source, and returned back into the input field, changing the text as the user is typing. 

This issue was introduced by https://github.com/mikeric/rivets/commit/998b77635fe14ed53d1cca8a8a8e5fbfdcf13f9b, where the event for `rv-value` was changed from `change` to `input`. 

I'd preferably not change our version of Rivets, or use a custom binder. Do you know of any other way I could solve this?

cc @rogierslag

**Comment by Duder-onomy** [comment]
@joostverdoorn Here is a jsfiddle I made that uses a custom binder that wraps the value binder but uses the `blur` event instead of the `input` event.

http://jsfiddle.net/p5482deg/1/

```javascript
rivets.binders['value-on-blur'] = {
    publishes: true,
    priority: 2000,
    bind: function(el) {
        this.event = 'blur';
        rivets._.Util.bindEvent(el, this.event, this.publish);
    },
    unbind : function() {
        rivets.binders.value.unbind.apply(this, arguments);
    },
    routine : function() {
        rivets.binders.value.routine.apply(this, arguments);
    }
}
```

You can change line `9` in this fiddle to `change` or really any DOM Input event.

Does this help?

**Comment by joostverdoorn** [comment]
Thanks @Duder-onomy, I decided to go with something along those lines, modifying the original `rv-value` binder instead of creating a new one. Appreciate the help!

**Comment by joostverdoorn** [comment]
I'll just close this.
