### ISSUE TITLE
How to show variable in attribule: href="/a/{ row.id }"

### ISSUE THREAD

**Issue by txthinking** [mikeric/rivets#481]
```<a href="/backend/role/{ row.id }">{ row.name }</a>```

`name` can show. but `id` can't be show

**Comment by Duder-onomy** [comment]
There are many ways to do this.

As a formatter: http://jsfiddle.net/bk0964k6/

```html
<a rv-href='"/backend/role/" | append row.id'>
        { row.name }
</a>
```

as a binder : http://jsfiddle.net/gr5cn9br/1/

```html
<a rv-backend-role-href='row.id'>
        { row.name }
</a>
```

as a component: http://jsfiddle.net/ahtonwLy/   
(components are new to me, so apologies if it is not as elegant as it could be)

```html
<backend-role-link row-id='row.id' row-name='row.name'></backend-role-link>
```

**Comment by txthinking** [comment]
@Duder-onomy Thank you very much.
