### ISSUE TITLE
Extend licensing to include MIT or BSD Revised license

### ISSUE THREAD

**Issue by gooftroop** [mikeric/rivets#482]
For various legal reasons, the usage of personally licensed source is not usually permitted in commercial or corporate licensed products. By employing the MIT License (looser terminology) or the BSD revised License, you retain authorship of rivets, yet allow for a legal distribution and usage of rivets.

**Comment by gooftroop** [comment]
Any update on this?

**Comment by tjcrowder** [comment]
The [license](https://github.com/mikeric/rivets/blob/master/LICENSE) is the MIT license, word-for-word.

**Comment by gooftroop** [comment]
ah, thanks!
