### ISSUE TITLE
I got "Uncaught TypeError: Cannot read property '0' of undefined"

### ISSUE THREAD

**Issue by derzunov** [mikeric/rivets#488]
I got "Uncaught TypeError: Cannot read property '0' of undefined" when I tried to use rivets.bundled.min.js

My adapters looks like 
Rivets.adapters[':'] = {
			observe: function(obj, keypath, callback) {
				obj.on('change:' + keypath, callback)
			},
			unobserve: function(obj, keypath, callback) {
				obj.off('change:' + keypath, callback)
			},
			get: function(obj, keypath) {
				return obj.get(keypath)
			},
			set: function(obj, keypath, value) {
				obj.set(keypath, value)
			}
		};

WTF?

**Comment by Duder-onomy** [comment]
@derzunov Here is a working JS fiddle using your supplied Adapter and Backbone Models. http://jsfiddle.net/wvvyw9c4/

Can you let me know what is diff about this JS fiddle and your implementation?
Event better, update the fiddle to make it not work?

Hope this helps.

**Comment by derzunov** [comment]
Hi, Greg!

I use it with RequireJS and I think Rivets is not work correctly with it...
Or I'm doing somth wrong...

define(
    [ 'rivets.bundled.min' ],
( Rivets ) ->
        Rivets.binders['style-bi'] = ( el, value ) ->
            el.style.setProperty('background-image', 'url("' + value + '")');

        return Rivets
)
Uncaught TypeError: Cannot set property 'style-bi' of undefined


__________________________________________

Дмитрий Ерзунов

Понедельник, 18 мая 2015, 11:23 -07:00 от Greg Larrenaga <notifications@github.com>:

**Comment by Duder-onomy** [comment]
Ahh, yes, There is something wrong with the bundled version of rivets and require.js

You need to shim rivets with [sightglass](https://github.com/mikeric/sightglass) in your require.js config.

```json
{
    "shim" : {
        "sightglass" : {
            "exports" : "sightglass"
        },
        "rivets" : {
            "deps" : ["sightglass"],
            "exports" : "rivets"
        }
    },
    "paths" : {
        "sightglass"                : "./vendor/sightglass/index",
        "rivets"                    : "./vendor/rivets/dist/rivets"
    }
}
```

This is related to : https://github.com/mikeric/rivets/issues/427


Please let me know if this fixes the issue.

Cheers.

**Comment by derzunov** [comment]
Oh, I have already fixed it this way exactly =)
I just wanted to find out how to work with bundle.

But thank you very much!
Have a nice day!


__________________________________________

Дмитрий Ерзунов

Понедельник, 18 мая 2015, 11:54 -07:00 от Greg Larrenaga <notifications@github.com>:
>Ahh, yes, There is something wrong with the bundled version of rivets and require.js
>You need to shim rivets with  sightglass in your require.js config.
>{
    "shim" : {
        "sightglass" : {
            "exports" : "sightglass"
        },
        "rivets" : {
            "deps" : ["sightglass"],
            "exports" : "rivets"
        }
    },
    "paths" : {
        "sightglass"                : "./vendor/sightglass/index",
        "rivets"                    : "./vendor/rivets/dist/rivets"
    }
}

**Comment by tjcrowder** [comment]
@derzunov If the issue is resolved, would you "close" the issue? Thanks.
