### ISSUE TITLE
How to programatically change a binded model?

### ISSUE THREAD

**Issue by b44rd** [mikeric/rivets#489]
Hi there, and thanks for making this amazing framework. 

I've recently met situations where I need to change, or enhance an existing model after it is binded to a view. For example by iterating over an external object, and adding properties from this into the object that is binded to a view through rivets. I can't get this to work properly, and I wonder if there's a good way of doing this without using view.unbind() and then rebinding, which to me seems a bit hackish?

**Comment by benliebert** [comment]
I have taken to making an overarching 'controller' class (which rivets
binds to) and then adding my data 'model' as a property of this.  I then
use jQuery $.extend to replace my model with no problems.  e.g.

var controller = function(model){
var Refresh = function(newModel){
$.extend(model, newModel);
}
};

Using this method, my controller properties (like Refresh) are static and
unchanged, but my data model can be repeatedly updated (e.g. by making an
AJAX call to save the entity)

On Tue, May 19, 2015 at 5:18 PM, b44rd <notifications@github.com> wrote:

> Hi there, and thanks for making this amazing framework.
>
> I've recently met situations where I need to change, or enhance an
> existing model after it is binded to a view. For example by iterating over
> an external object, and adding properties from this into the object that is
> binded to a view through rivets. I can't get this to work properly, and I
> wonder if there's a good way of doing this without using view.unbind() and
> then rebinding, which to me seems a bit hackish?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeric/rivets/issues/489>.
>



-- 
ben liebert
blackball software ltd, www.blackballsoftware.com

**Comment by b44rd** [comment]
Thanks! I will have a go at trying this out and see if it helps. 

My problem is mainly iterating over the initially binded object using jQuery.each(), and changing properties. It seems like I can say this.property = 'Something', but the next time I need to do something with the same object, it kind of do not respond to anything. 

Let's say I've got a view saying something ala:

<div id="productwrap">
  <div rv-each-product="products">
    <span rv-unless="product.inactive" rv-class-selected="product.selected" rv-on-click="controller.somefunction">Product</span>
  </div>
</div>

And in my script, I bind it to the DOM something like:

function rivets_createview (el, data){
  return rivets.bind(el, data);
};

var myview = rivets_createview(
  $('#productwrap'),
  {
    products: someobject,
    controller: someotherobject
  }
);

This will work fine. If I start iterating over the products object using $.each() and setting the prodict.selected property to true, it still seems to work. Though, when I click the item, something strange has happened all of a sudden, and I cannot find out what is wrong. 

Is there any reason for something ala this to happen, or am I doing something wrong?
