### ISSUE TITLE
Ignore null or undefined values?

### ISSUE THREAD

**Issue by benknight** [mikeric/rivets#493]
Hey there, I'd like to do this in my code:

`<img src="http://placehold.it/1200x628" rv-src="data.imageSrc">`

Where the placeholder shows when `data.imageSrc` is `null` or `undefined`.  Is this possible with Rivets.js?

**Comment by Duder-onomy** [comment]
you would probably want to do something like, rivets not needed. 

```html
<img rv-src='data.imageSrc' onerror='this.src = "http://placehold.it/1200x628";'></img>
```

There is also this custom binder example: https://github.com/mikeric/rivets/wiki/Custom-Binders#src-strict

Or you could do something like `rv-src-or-placeholder`

```javascript
rivets.binders['src-or-placeholder'] = function(el, imageSrc) {
    el.onerror = function() {
        el.src = el.getAttribute('placeholder');
    };

    el.src = imageSrc;
}
```

Then in your html

```html
<img rv-src-or-placeholder='data.imageSrc' rv-placeholder='data.placeholderSrc'>
```

* you would need to put the placeholder source in your bound model. 

I hope this helps.

**Comment by benknight** [comment]
Wow this is a very thorough breakdown of my options.  Thanks!
