### ISSUE TITLE
Binding to ES5 getters

### ISSUE THREAD

**Issue by jiaweihli** [mikeric/rivets#499]
I'm trying to use one-way binding on ES5 getters, but it looks like rivets overrides them.  Is there any workaround?

**Comment by jiaweihli** [comment]
Mmm...seems like only functions are supported?

**Comment by Leeds-eBooks** [comment]
Rivets use setters and getters in its `.` adapter, to facilitate observing changes to the model. If you define your own adapter, you will be able to do it differently. But you'll have to find your own way of observing changes.

**Comment by jiaweihli** [comment]
Makes sense.  For other people who might stumble on this thread: the built-in `.` adapter only supports functions and attributes.
