### ISSUE TITLE
Anyone got rivetsjs working with Selenium IDE?

### ISSUE THREAD

**Issue by benliebert** [mikeric/rivets#503]
We've just started using the Selenium IDE, which operates as a Firefox extension. I have found that when Selenium inserts text, it appears visually within Firefox, but my rivets model does not detect the change and save it back to the model.

It works fine on SELECT elements, just not input[type=text].  

Any ideas appreciated

![image](https://cloud.githubusercontent.com/assets/2273767/8492591/08eb1ada-21a0-11e5-916a-0dd2975ca966.png)

**Comment by Duder-onomy** [comment]
Hey,

Only a few rivets binders publish values back to the bound model when observed elements are changed.
The `rv-checked`, `rv-unchecked` and the `rv-value` binders. 

If you look at the rivets source for these binders: https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L69, you can see that they are listening for the 'input' event on the bound element. You can see that code in the `bind` method of the `value` binder. 

So, back to your issue, my feeling is that when Selenium is inserting text into your inputs, it does not fire an `input` event. 

Can you confirm that this is true? That Selenium is not firing an 'input' event when updating `<input>` values?

---

If the above is true, some ways around it. 

You can put the `rv-value` binder behind a [facade](https://carldanley.com/js-facade-pattern/), then swap it out based on the ENV. When you are doing your selenium testing, the definition of the `rv-value` binder would use the change event, or the paste, or just poll the DOM for changes.  I can help you write this if the above is true.

You can manually trigger the 'input' event on the element in question before running your assertions?
I am not as familiar with Selenium, but we have that in our Mocha tests. 

```javascript
// some test setup
// put some value into some input
$(someElement).trigger('input');
// do assertions on the inputs value.
```

I hope this helps!

**Comment by benliebert** [comment]
Thanks Greg, good idea re the facade. I was thinking along those lines of
the event not firing. Sure enough, Selenium has another function (sendKeys)
which DOES cause rivets to run.  I understand that this function injects
itself at a much higher level and therefore more likely to cause the
browser to fire an even that rivets can hear.

I would prefer to have all methods working, so the facade is a good idea.
Will let you all know how it goes.

On Tue, Jul 7, 2015 at 6:04 AM, Greg Larrenaga <notifications@github.com>
wrote:

> Hey,
>
> Only a few rivets binders publish values back to the bound model when
> observed elements are changed.
> The rv-checked, rv-unchecked and the rv-value binders.
>
> If you look at the rivets source for these binders:
> https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L69, you
> can see that they are listening for the 'input' event on the bound element.
> You can see that code in the bind method of the value binder.
>
> So, back to your issue, my feeling is that when Selenium is inserting text
> into your inputs, it does not fire an input event.
>
> Can you confirm that this is true? That Selenium is not firing an 'input'
> event when updating <input> values?
> ------------------------------
>
> If the above is true, some ways around it.
>
> You can put the rv-value binder behind a facade
> <https://carldanley.com/js-facade-pattern/>, then swap it out based on
> the ENV. When you are doing your selenium testing, the definition of the
> rv-value binder would use the change event, or the paste, or just poll
> the DOM for changes. I can help you write this if the above is true.
>
> You can manually trigger the 'input' event on the element in question
> before running your assertions?
> I am not as familiar with Selenium, but we have that in our Mocha tests.
>
> // some test setup// put some value into some input
> $(someElement).trigger('input');// do assertions on the inputs value.
>
> I hope this helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeric/rivets/issues/503#issuecomment-118940616>.
>



-- 
ben liebert
blackball software ltd, www.blackballsoftware.com

**Comment by Leeds-eBooks** [comment]
@benliebert I am closing this issue as it appears to be resolved. Please open again if not!
