### ISSUE TITLE
Creating a temporary property on an item results in 'Cannot redefine property' after rebinding

### ISSUE THREAD

**Issue by benliebert** [mikeric/rivets#506]
I have a model that I am binding to Rivets, like so:

```
var model = {
    People: [
        {FirstName: 'Larry'},
        {FirstName: 'Bruce'}
    ]
}
```

I then bind the People array to my view using data-each-x="model.People".  When the user clicks a 'delete' button, I set a property within the event handler, like this.

```
function DeleteItem(ev, item){
    item.x.IsDeleted = true;
    saveToServer(bla bla, function(){
        // Success handler - continue
    }, function(errorMsg){
        // Error handler
        item.x.IsDeleted = false;
    }
}
```

Now, the IsDeleted property is NOT on the model items when the view is bound - thanks to Javascript I can create it dynamically.  And this all works great.  Except that later when I refresh my model:

```
function Refresh(newModel){
    this.model = newModel;
}
```

And I get this error:

Potentially unhandled rejection [1] TypeError: Cannot redefine property: Test
    at defineProperty (native)
    at Function.defineProperty (lib/traceur-runtime.js:177:5)
    at Object.Rivets.public.adapters...observe (lib/rivets.js:1232:16)
    at Observer.set (lib/sightglass.js:148:28)
    at new Observer (lib/sightglass.js:21:9)
    at Object.sightglass (lib/sightglass.js:4:10)
    at Binding.Rivets.Binding.Binding.observe (lib/rivets.js:560:21)
    at Binding.__bind [as observe] (lib/rivets.js:7:61)
    at Binding.Rivets.Binding.Binding.parseTarget (lib/rivets.js:572:30)
    at Binding.__bind [as parseTarget] (lib/rivets.js:7:61)

Any ideas?  It is REALLY useful to be able to create temp properties like this.

**Comment by Leeds-eBooks** [comment]
Why are you doing `this.model = newModel`? Is that absolutely necessary? That will break all the rivets getters and setters, so it's bound to lead to issues. And of course any properties you applied to the model will be lost.

Additionally, the second argument to event handlers is a scope object, not the item.

**Comment by benliebert** [comment]
Hi,

Technically I use jQuery's extend() method to replace my model, however I
have found this works.  I think the naming is misleading because in fact I
have a parent class above 'model' which is what Rivets is actually bound to
- so 'model' becomes just a property.

Out of interest - is there a 'best practice' way to update your model?

And no thoughts on the question about temp properties?



On Fri, Jul 10, 2015 at 7:07 PM, Ben Styles <notifications@github.com>
wrote:

> Why are you doing this.model = newModel? Is that absolutely necessary?
> That will break all the rivets getters and setters, so it's bound to lead
> to issues. And of course any properties you applied to the model will be
> lost.
>
> Additionally, the second argument to event handlers is a scope object, not
> the item.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeric/rivets/issues/506#issuecomment-120259212>.
>



-- 
ben liebert
blackball software ltd, www.blackballsoftware.com

**Comment by Leeds-eBooks** [comment]
The way I update my models is by changing each of the "end values". I don't know about best practice, but this is the only way I've found that works. It's the only you can trigger the getters and setters that observe for changes. There are different ways to do this, one example of a way I've done it before is (using ES6):

```js
// destObj would be the model rivets is bound to, newObj is the parsed JSON retrieved from the server

function updateUser(newObj, destObj) {
  const dest = destObj || userObj,
        iterate = (val, key) => {
          const newVal = newObj[key];

          if (_.exists(newVal)) {

            if (_.isString(newVal) /* && newVal.trim() */) {
              dest[key] = newVal;
            } else if (Array.isArray(newVal) && !_.isEqual(val, newVal)) {
              if (!Array.isArray(val)) dest[key] = [];
              else dest[key].length = 0;
              dest[key].push(...newVal);
            } else if (_.isPlainObject(newVal)) {
              if (_.isPlainObject(val)) updateUser(newVal, dest[key]);
              else dest[key] = newVal;
            }

          }
        };

  _.each(dest, iterate);
}
```

It's pretty ugly but it works. If I knew exactly what I was retrieving from the server, I could be much cleaner about it.

As long as you are only changing values, not objects, any "temporary" properties should remain.

**Comment by benliebert** [comment]
​Actually just found this - https://github.com/mikeric/rivets/issues/131​,
which looks like the right way to do it.  I haven't implemented yet....

On Mon, Jul 13, 2015 at 7:26 AM, Ben Styles <notifications@github.com>
wrote:

> The way I update my models is by changing each of the "end values". I
> don't know about best practice, but this is the only way I've found that
> works. It's the only you can trigger the getters and setters that observe
> for changes. There are different ways to do this, one example of a way I've
> done it before is (using ES6):
>
> // destObj would be the model rivets is bound to, newObj is the parsed JSON retrieved from the server
> function updateUser(newObj, destObj) {
>   const dest = destObj || userObj,
>         iterate = (val, key) => {
>           const newVal = newObj[key];
>
>           if (_.exists(newVal)) {
>
>             if (_.isString(newVal) /* && newVal.trim() */) {
>               dest[key] = newVal;
>             } else if (Array.isArray(newVal) && !_.isEqual(val, newVal)) {
>               if (!Array.isArray(val)) dest[key] = [];
>               else dest[key].length = 0;
>               dest[key].push(...newVal);
>             } else if (_.isPlainObject(newVal)) {
>               if (_.isPlainObject(val)) updateUser(newVal, dest[key]);
>               else dest[key] = newVal;
>             }
>
>           }
>         };
>
>   _.each(dest, iterate);
> }
>
> It's pretty ugly but it works. If I knew exactly what I was retrieving
> from the server, I could be much cleaner about it.
>
> As long as you are only changing values, not objects, any "temporary"
> properties should remain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeric/rivets/issues/506#issuecomment-120755505>.
>



-- 
ben liebert
blackball software ltd, www.blackballsoftware.com

**Comment by Leeds-eBooks** [comment]
Closing as this appears to be resolved.
