### ISSUE TITLE
Directions for FE newbs

### ISSUE THREAD

**Issue by ORESoftware** [mikeric/rivets#509]
Looking forward to using this lib.

I saw the instructions on the Rivets website to install via Bower like so

```bower install rivets```

I also saw that its only hard dependency is 'sightglass' the prehistoric Object.observe monster

I am using AMD and I see this at the bottom of the rivets.js file in the Bower installation:

```javascript
 if (typeof (typeof module !== "undefined" && module !== null ? module.exports : void 0) === 'object') {
    module.exports = Rivets.factory(require('sightglass'));
  } else if (typeof define === 'function' && define.amd) {
    define(['sightglass'], function(sightglass) {
      return this.rivets = Rivets.factory(sightglass);
    });
  } else {
    this.rivets = Rivets.factory(sightglass);
  }
```

so, I assume that I have to use RequireJS to define sightglass as a dependency for rivets. So I am asking you to please document how to use Rivets with RequireJS properly, otherwise you force us to have to look at source and guess around which is really not ideal. I haven't tried it yet, and it might be easy and it might be hard, but I may be speaking for my future self in 5 minutes or something other poor developer who might have to guess around more than I have.

thanks!

**Comment by ORESoftware** [comment]
also, I personally don't like that there are no semi-colons in sightglass, f*ck that hipster shit

**Comment by Duder-onomy** [comment]
Hi, 
To use rivets with require.js you need to shim it with sightglass.

In you requre.js config:
```javascript
"shim" : {
        "sightglass" : {
            "exports" : "sightglass"
        },
        "rivets" : {
            "deps" : ["sightglass"],
            "exports" : "rivets"
        },
},
"paths" : {
        "sightglass"                : "./vendor/sightglass/index",
        "rivets"                    : "./vendor/rivets/dist/rivets"
}
```

Relates to: https://github.com/mikeric/rivets/issues/427 https://github.com/mikeric/rivets/issues/488

Shimming dependencies is something that developers using require.js need to do quite often, so I am not sure if warrants specific instructions in the rivets repo. That being said your issue has been noted and will be revisited if there is continued confusion after the upcoming changes.

If this helps you can you please close this issue. We are trying to keep the issue real and few.
Thanks

**Comment by ORESoftware** [comment]
yeah that requirejs configuration worked for me, thanks
