### ISSUE TITLE
Is it support IE6-10?

### ISSUE THREAD

**Issue by RuyiDu** [mikeric/rivets#514]
There are many people what also use window xp system and IE6 in our country.

So i need to test project on ie6, but i found it can work fine on IE11, and the others IE version can not.

Is it ? 

Thanks

**Comment by pppdns** [comment]
I don't think it supports IE6, not many tools support IE6 on the internet as such an ancient browser requires too much time and puts so many limitations in the implementation. I think all of us feel your pain that you have to support IE6... :(

**Comment by RuyiDu** [comment]
LOL.... You a really fortunate.....
