### ISSUE TITLE
DOM not updated when data is changed (arrays in arrays)

### ISSUE THREAD

**Issue by dave-islive** [mikeric/rivets#519]
I have an object containing an array, which contains other arrays. the initial binding and display works perfectly, but when an item is changed it will not update the DOM somehow.

I use this object:
```
var rivetsData = {
  agendaItems: [
    ['2015-09-16', [{ startTime: '09:00', endTime: '10:00' }, { startTime: '14:00', endTime: '15:00' }]],
    ['2015-09-17', [{ startTime: '10:00', endTime: '11:00' }, { startTime: '15:00', endTime: '16:00' }]],
    ['2015-09-18', [{ startTime: '11:00', endTime: '12:00' }, { startTime: '16:00', endTime: '17:00' }]],
    ['2015-09-19', [{ startTime: '12:00', endTime: '13:00' }, { startTime: '17:00', endTime: '18:00' }]],
    ['2015-09-20', [{ startTime: '13:00', endTime: '14:00' }, { startTime: '18:00', endTime: '19:00' }]],
    ['2015-09-21', [{ startTime: '14:00', endTime: '15:00' }, { startTime: '19:00', endTime: '20:00' }]]
  ]
};
```

and it is bound to this html:
```
<div class="extra-agenda-holder">
   <div class="agenda-item" rv-each-agendaitem="agendaItems" rv-on-click="openAgendaItem">
      <span class="agendaitem-date" rv-text="agendaitem | arrayindice 0">datum</span>
      <div style="position: relative; left: 20px;" class="agendaitem-parts">
         <div class="agendaitem-part" rv-each-agendaitempart="agendaitem | arrayindice 1">
            <span rv-text="agendaitempart.startTime">start tijd</span>
            <span rv-text="agendaitempart.endTime">eind tijd</span>
         </div>
      </div>
   </div>
</div>
```

arrayindice is a formatter I use, but it is oneway only:
```
rivets.formatters.arrayindice = function(value, index) {
  return value[index];
};
```

Is there anything else I need to do to make it update again?

**Comment by dave-islive** [comment]
Also, when I add an element to the array rivets will not update the associated html elements.

**Comment by dave-islive** [comment]
I updated the object as follows:
```
var rivetsData = {
  agendaItems: [
    { date: '2015-09-16', parts: [{ startTime: '09:00', endTime: '10:00' }, { startTime: '14:00', endTime: '15:00' }]},
    { date: '2015-09-17', parts: [{ startTime: '10:00', endTime: '11:00' }, { startTime: '15:00', endTime: '16:00' }]},
    { date: '2015-09-18', parts: [{ startTime: '11:00', endTime: '12:00' }, { startTime: '16:00', endTime: '17:00' }]},
    { date: '2015-09-19', parts: [{ startTime: '12:00', endTime: '13:00' }, { startTime: '17:00', endTime: '18:00' }]},
    { date: '2015-09-20', parts: [{ startTime: '13:00', endTime: '14:00' }, { startTime: '18:00', endTime: '19:00' }]},
    { date: '2015-09-21', parts: [{ startTime: '14:00', endTime: '15:00' }, { startTime: '19:00', endTime: '20:00' }]},
    { date: '2015-09-21', parts: [{ startTime: '15:00', endTime: '16:00' }, { startTime: '20:00', endTime: '21:00' }]}
  ]

};
```
but when an array item is added or deleted it simply will not update the view

**Comment by Leeds-eBooks** [comment]
@dave-islive How are you adding/removing items?

**Comment by dave-islive** [comment]
with push() and delete

**Comment by dave-islive** [comment]
also altering the items in an array will not update the view

**Comment by Leeds-eBooks** [comment]
Hmm, push should work. But delete will not. The way Rivets watches arrays is by stubbing the methods on `Array.prototype`.

**Comment by dave-islive** [comment]
so how can I change an item in the array and tell rivets to update it?

**Comment by snehalnayan** [comment]
I have had this issue in the past and it specifically seems to happen for deeply nested objects, so array within array or object within an object

Lot of times rivets would pick up the change if an item with a deeply nested object was changed but then at times it would not.

So I just use the update() method to tell rivets that my data has changed and that seems to work

**Comment by Leeds-eBooks** [comment]
As I understand it, Rivets cannot watch for properties within an object inside an array. What I do, when I'm binding to objects within arrays, is rebuild the whole array when one of the objects updates. This sounds costly but it's not at all (unless you're dealing with thousands of objects). I do something like the following:

```javascript
const model = {
  conversations: []
}

function fetch() {
  // do some server communication and return response.conversations
  if (model.conversations.length) model.conversations.length = 0;
  model.conversations.push(
    ...response.conversations
  )
}
```

**Comment by dave-islive** [comment]
Thanks for your reply, I changed the layout of the object and only use push and splice and it works like a charm :)
