### ISSUE TITLE
Javascript adapter isn't detecting changes to array elements

### ISSUE THREAD

**Issue by anyweez** [mikeric/rivets#520]
The standard Javascript adapter isn't detecting when I make changes to bound array elements. In the following example, I would expect the `numbers` binding to be updated when the underlying array is modified (i.e. when `changeNum` is called).

```html
<html>
<head>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/rivets/0.8.1/rivets.bundled.min.js"></script>
  <script type="text/javascript">
    var numbers = [111, 222, 333];

    window.addEventListener('load', function() {
      rivets.bind(document.getElementById('numbers'), {numbers: numbers});
     });

     function changeNum() {
       numbers[0] = 5;
     }
  </script>
</head>
<body>
  <button onclick="changeNum()">Add a number</button>
  <div id="numbers">{ numbers }</div>
</body>
</html>
```

Updates *do* occur when I push or pop from the array, but not when I modify elements. Is this expected? If so, what's the right way to modify an array that'll trigger binding updates (ideally with the standard JS adapter but OK if not!)?

FYI I'm also asking the same question on [StackOverflow](http://stackoverflow.com/questions/32750527/detecting-changes-to-arrays-with-rivetsjs) in case I'm simply missing something in the API.

**Comment by Leeds-eBooks** [comment]
This is expected behaviour I'm afraid. The standard adapter actually stubs/proxies the native array methods to watch for changes. So what I do is rebuild the array from scratch each time there is a change. Basically, set the `array.length` to `0`, then `push()` the new array (ES6 makes this easy with `push(...newArray)`.

**Comment by Leeds-eBooks** [comment]
Let me know if this answers your question so we can close the issue – or feel free to ask further questions.

**Comment by anyweez** [comment]
Cool, thanks Ben -- makes sense though its unfortunate. Feel free to close!

**Comment by Leeds-eBooks** [comment]
What I should have added is that if your array is an array of objects, then changes _are_ observed correctly. Changing a property on an object in an array of objects _will_ update the `rv-each` binding.
