### ISSUE TITLE
Initiate rivets through require.js

### ISSUE THREAD

**Issue by b44rd** [mikeric/rivets#523]
Hi there! Having problems with using rivets in combination with require.js. This is basically what I want to achieve, but for some reason it simply do not work as expected. When debugging using debugger, everything seems normal, but the model do not get binded to the DOM. No error messages anywhere.

Any idea on what could be the issue here? Thanks a ton. 

```javascript
define([
    "jquery",
    "rivets",
],
function($, rivets) {
    rivets.bind(
        $("#someid"), 
        {   
            somelist: {
                items: [
                    { name: "Item 1" },
                    { name: "Item 2" }
                ]
            } 
        }
    ); 
});
```

**Comment by Duder-onomy** [comment]
HI, 
You will need to shim rivets with its sightglass dependency, 
something like this:

```javascript
"shim" : {
        "sightglass" : {
            "exports" : "sightglass"
        },
        "rivets" : {
            "deps" : ["sightglass"],
            "exports" : "rivets"
        },
},
"paths" : {
        "sightglass"                : "./vendor/sightglass/index",
        "rivets"                    : "./vendor/rivets/dist/rivets"
}
```

Relates to: https://github.com/mikeric/rivets/issues/509


Please close this issue if it helps you.

**Comment by b44rd** [comment]
Awesome, thanks a ton. This solved it. :)
