### ISSUE TITLE
Listen changes on object (from rv-each)

### ISSUE THREAD

**Issue by thiagof** [mikeric/rivets#526]
I'm trying to catch any changes from the form items, that are in a loop. It is an array of objects, something like:

```
<div rv-each-survey="pageItems"
        rv-observe="survey">
<input rv-value="survey.name" />
</div>
```

On this observe binding, I'm trying to catch the changes from the survey object, but had no success.

Any ideas to point me in the right direction? Thanks for your time.

**Comment by Leeds-eBooks** [comment]
What does your observe binder look like?

**Comment by thiagof** [comment]
It is this way. The observable gets called for initial binding (reconfigure type), which I suspect means rivets getting over the object properties and getting in front of my observable. None change gets triggered than.

```js
      observe: {
        bind: function(el) {
          var adapter = this.view.adapters[this.observer.key.i],
              model = this.model,
              keypath = this.keypath,
              value = adapter.get(model, keypath),
              callback = $(el).attr('observe-callback');

          this.observable = function(changes) {
            var cb = adapter.get(model, callback);
            if (cb)
              cb.call(el, changes);
          };

          // sightglass(value, '', function() {
          //   console.log(arguments);
          // });

          Object.observe(value, this.observable, ["add", "update", "delete"]);
        },
        unbind: function(el) {
          var adapter = this.view.adapters[this.observer.key.i],
              model = this.model,
              keypath = this.keypath,
              value = adapter.get(model, keypath);

          Object.unobserve(value, this.observable);
        },
        routine: function(el, value) {
          console.log(value);
        }
      }
```

**Comment by Leeds-eBooks** [comment]
I'm afraid I'm a little confused by this. Observing objects is done by adapters, not binders. You're going to run into conflicts if you try to observe an object using a binder because the object is already being observed by the default rivets `'.'` adapter, which works by replacing properties with getters and setters. Remember that `rv-observe="survey"` is actually `rv-observe=".survey"`.

What is your actual use case? Why do you need to track changes? I am pretty sure there will be a better way that is more idiomatic to rivets.

**Comment by thiagof** [comment]
I'm using rivets for some time but not fully got how to workout with the api (its a hard cofeescript).

The use case (here abstracted) is to auto-save items that get changes from the ui.

**Comment by Leeds-eBooks** [comment]
Ah ok. So what I do in this situation is something like this:

```html
<div rv-each-survey="pageItems">
  <input rv-value="survey.name" rv-on-input="save">
</div>
```

```javascript
var model = {
  save: function(event, scope) {
    var survey = scope.survey
    yourSaveAction(survey)
  }
}
```

`rv-each` passes each item in the array to its children's `rv-on-{event}` event handlers as the `scope` argument, under the name you use in `rv-each-{name}`. Bear in mind that this will call `yourSaveAction` on every keypress. If you want to debounce the input you can use something like `underscore.js`'s `_.debounce()`.

By the way, if you're having a hard time with coffeescript, we have an es6 rewrite in the works: https://github.com/mikeric/rivets/pull/511

**Comment by thiagof** [comment]
Yeah, true, that should fit the use case.

Thanks for mentioning the branch, I should use it for reference!

**Comment by Leeds-eBooks** [comment]
Great, no problem. Going to close this for now.

**Comment by Leeds-eBooks** [comment]
Whoops, you already closed it!
