### ISSUE TITLE
Concat binder value

### ISSUE THREAD

**Issue by shina** [mikeric/rivets#530]
Hello guys,

I'm wondering how do I concatenate a binder value. Eg.:

```javascript
rv-checked="model.name + someVar"
// where model.name is a string
// and someVar a string with value "person"
```

So, my purpose is to use the value `model.name.person`

thanks

**Comment by Leeds-eBooks** [comment]
If I understand correctly, you want to do the equivalent of `model.name['person']`, in other words, _dynamically_ reference a property on the `model.name` object. Is that correct?

**Comment by shina** [comment]
Exactly! Thanks to brighten my question hehe

**Comment by Leeds-eBooks** [comment]
No problem, just wanted to be clear. But unfortunately, I haven't found a way to do this. Rivets reads your binder attributes on `.bind()` so it would require a fairly big structural change, I think, to be able to support dynamic binder keypaths.

**Comment by shina** [comment]
I see.

Does the "each" binder have to re-bind the elements everytime the list changes?
Maybe it has a clue to achieve it.

I really tried to hack the es6 version but it is too hard for me to understand. heheh

**Comment by Leeds-eBooks** [comment]
Yes, good point, the each binder does re-bind automatically. If there's any way to do this _without_ hacking rivets, it will be with a [custom adapter](http://rivetsjs.com/docs/guide/#adapters-creating). You'd have to find a way to evaluate the keypath. So if you set the custome adapter symbol as `[`, your html might look like `rv-checked="model.name[someVar"` and then in your adapter methods you'd have to evaluate `someVar` as a keypath on the whole model. If you define your adapter in the same scope as where you define your model, this would be simple. Is that a viable route for you?

**Comment by shina** [comment]
Yes. I'll try it.

**Comment by Leeds-eBooks** [comment]
@shina Did you sort this? I'm closing for now.
