### ISSUE TITLE
Static strings can't contain pipe character

### ISSUE THREAD

**Issue by pppdns** [mikeric/rivets#533]
I just came accross this one, seems like static strings passed to binders are sensitive about the string's content. If the string contains a pipe `|` character the binding will fail.

Test case:
`<div rv-my-binder="'string conta|ning pipe character' | date"></div>`

Where it fails in `view.coffee`:
`pipes = (pipe.trim() for pipe in declaration.split '|')`
https://github.com/mikeric/rivets/blob/176f391308dfa6e7ca734f57caa8224239d4899d/src/view.coffee#L37

rivets tries to split the formatter parts at pipes but it also (wrongly) finds pipes in static strings.

**Comment by pppdns** [comment]
what about splitting the string using some clever regexp maybe?

**Comment by Leeds-eBooks** [comment]
If you can submit a PR with the regexp I will merge it!

**Comment by blikblum** [comment]
PR https://github.com/mikeric/rivets/pull/487 seems to handle that

Needs some tests though

**Comment by Leeds-eBooks** [comment]
Cool. Do you reckon you could provide those tests?

**Comment by blikblum** [comment]
Sure

**Comment by blikblum** [comment]
Done #548

**Comment by Leeds-eBooks** [comment]
Merged
