### ISSUE TITLE
Binding with getters/setters not working

### ISSUE THREAD

**Issue by babbelnedd** [mikeric/rivets#536]
The initial part is working, not surprising.
But the `set` part isn't triggering an update.

http://jsfiddle.net/44nuf9qL/1/

**Comment by Duder-onomy** [comment]
The way rivets observes changes on POJO's is by wrapping all properties in getters and setters. It does this for the default `dot` adapter. This is what lets rivets work all the way back to old IE and it removes the need for a digest/diffing cycle. It does not surprise me that if you define your own getters and setters they will not be respected.  If you must use getters and setters on your own bound objs, I recommend defining your own adapter. You could define an adapter that used any other symbol as a property accessors and then teach rivets how to observe the new objects. More on that [here](http://rivetsjs.com/docs/guide/#adapters)

Please let us know if this helps you. 
Please close this issue if you don't need anything else.
