### ISSUE TITLE
fire function after rivets binding completed?

### ISSUE THREAD

**Issue by jtrutwin** [mikeric/rivets#542]
I'm loading a large table of events using rivets and as the page opens the user sees the rivets data binding tags:  e.g.  {event.name} until the data has been fetched via ajax and bound to the dom elements via rivets.bind()

Is there a way I can fire a function after all binding has completed so I can hide the table body until all the events are loaded?  Something like rivets.bind(...).done(function () { ... } );

Sorry this is kind of worded poorly, let me know if additional information is needed.

**Comment by Leeds-eBooks** [comment]
`rivets.bind()` is synchronous, so you could call `rivets.bind()` after all your Ajax calls have returned, then unhide your table. Or use `Promise.all()` with your Ajax calls to know when they're all done. This isn't really a rivets issue per se, it's up to you what you do before and after your Ajax calls.

**Comment by Leeds-eBooks** [comment]
@jtrutwin Did this solve your issue? I am closing it for now, I can reopen if it didn't.

**Comment by jtrutwin** [comment]
Yes @Leeds-eBooks - I should've done more investigating before opening this ticket.  Thanks for your reply!

**Comment by Leeds-eBooks** [comment]
@jtrutwin great, no problem!
