### ISSUE TITLE
Should we keep bower.json in es6 rewrite?

### ISSUE THREAD

**Issue by aarjithn** [mikeric/rivets#556]
I cannot find rivets in the bower registry http://bower.io/search/?q=rivets. Also npm is now very popular for front end with flat dependencies. Is it worthy to keep bower.json in the es6 rewrite?
Does anybody here use rivets with bower?

**Comment by Jmeyering** [comment]
`bower search rivets` turns up rivets as the first results, not sure why its not showing in the registry online.

I use bower and have 0 desire to use npm to manage front end dependencies.
