### ISSUE TITLE
Bind rv-value as number?

### ISSUE THREAD

**Issue by Jmeyering** [mikeric/rivets#559]
I'm looking to bind the value of an input type as a number on a model, but I can't seem to get it to bind as anything but a string.

```
          <input rv-value="metric.number | int < number" type="number">
```

This is the general gist of the code, the `int` formatter returns a `parseInt` on the value, and console logging tells me that its running just fine. However the properties being set on my model are all set as strings. Any idea how to force rivets to save the value to the model as a number?

**Comment by jccazeaux** [comment]
Hi, to achieve this, your `int` formatter must be bi-directionnal
```javascript
rivets.formatters["int"] = {
  read: function(value) {
    // Return value without transform : the input doesn't care the type
    return value
  },
  publish: function(value) {
    // Publish a number in the model 
    return parseNumber(value)
  }
};
```

Full example here : https://jsfiddle.net/jccazeaux/ch8s0c80/

You don't need to use ` < number` as `metric.number` is already bound to your input.

**Comment by Jmeyering** [comment]
Perfect! thanks so much!
