### ISSUE TITLE
use item from array in each binding

### ISSUE THREAD

**Issue by babbelnedd** [mikeric/rivets#565]
I want to use an `each` helper and use the actual object at the same element.

Example

```
<select>
  <!-- rv-label in this case -->
  <optgroup rv-label="tier.name" rv-each-tier="tiers">
    <option rv-each-item="tier.arr">{item.foo}</option>
  </optgroup>
</select>
```

**Comment by blikblum** [comment]
Can you add a jsfiddle or codepen sample?

**Comment by babbelnedd** [comment]
.. I'm sorry. Apparently it was a fault on my end. Got it working.

Here is a [working fiddle](https://jsfiddle.net/neqvjgfm/6/) for the case you want to reference this issue later.

**Comment by Duder-onomy** [comment]
Going to close this as it appears resolved.
