### ISSUE TITLE
When HTML attribute is empty, binders receives 0 instead of undefined

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#567]
### Issue
If binder is called like that
```html
<div rv-my-binder></div>
```
Or
```html
<div rv-my-binder=""></div>
```
It will receive 0 instead of null (or undefined ?)
See fiddle here : https://jsfiddle.net/jccazeaux/yqnubqkz/

### Cause
The cause is in function `parseType` from `parsers.coffee`. In case of no HTML attribute we go into this case
```javascript
else if (isNaN(Number(string)) === false) {
  value = Number(string)
}
```
because
```javscript
     Number(null) == Number("") == 0
```

I think binder should receive `undefined` when HTML attribute is empty or not specified. If you agree i'll send the PR

**Comment by Duder-onomy** [comment]
:+1: Agreed. We all know `0` will be coerced into a `false` but having it pass `undefined` is semantically correct. 

My only issue, take the `required` attribute on the input tag for example. If the attribute is present, that is enough to warrant a `true` value.  It does not have to be explicitly set as `required='true'`.  
But..... That is weird anyways. 

Thoughts?

**Comment by jccazeaux** [comment]
As you say it's weird, but it's still possible. The binder's code would have to consider ```undefined``` as ```true```.

**Comment by Duder-onomy** [comment]
I am all for this. It is a minor but important improvement. 

I will attach it to the 0.9 release. If anyone has any objections, please chime in. 

@jccazeaux Will you champion this one for us?

**Comment by Duder-onomy** [comment]
Closing.
