### ISSUE TITLE
Binding to Backbone.Collection with the data-each- binding

### ISSUE THREAD

**Issue by dominicglenn** [mikeric/rivets#57]
I'm trying to bind to a Backbone Collection in my view using rivets and have been using the following code to ensure that they work in the same way as other models do:

```
var IterableCollection = {};
IterableCollection.prototype = {
    get: function(id){
        if(id === 'models'){
            return this.models;
        }
        return Backbone.Collection.prototype.get.call(this, id);
    },
    add: function(models, options){
        var ret = Backbone.Collection.prototype.add.apply(this, arguments);
        options || (options = {});
        this.trigger('change:models', this, this.models);
        return ret;
    },
    remove: function(models, options){
        var ret = Backbone.Collection.prototype.remove.apply(this, arguments);
        options || (options = {});
        this.trigger('change:models', this, this.models);
        return ret;
    },
    reset: function(models, options){
        var ret = Backbone.Collection.prototype.reset.apply(this, arguments);
        options || (options = {});
        this.trigger('change:models', this, this.models);
        return ret;
    }
};
```

Then I make sure my collection inherits from this:

```
_.extend(MyCollection.prototype, IterableCollection.prototype);
```

This has made it so that in the templates I can simply pass the collection to the rivets binding, and correctly bind to change events on the collection.

Is this the correct way that it should be implemented? It feels vaguely hackish..

My other point would be that it may be useful to have a wiki somewhere or something that we can use to put in useful snippets (perhaps like this one) that would be useful for people to use in conjunction with rivets for Backbone, or Spine or perhaps another framework?

**Comment by DominicTobias** [comment]
Anyone know why this isn't working? Using the adapter posted by @wulftone 

http://jsfiddle.net/ferahl/fwhuf/86/
