### ISSUE TITLE
Question: Using rv-class with a camelCase class name. Is there a more elegant solution?

### ISSUE THREAD

**Issue by MeoMix** [mikeric/rivets#570]
Hey there,

I was attempting to set a class using the following:

```
rv-class-fooBar='model.isActive'
```

This did not work because capital letters are invalid syntax in HTML attributes. So, `fooBar` was converted to `foobar` and the incorrect class was applied to the element.

I created the following binder + formatter to workaround the issue:

```
rivets.binders.setclass = (el, options) => {
  el.classList.toggle(options.className, options.hasClass);
}

rivets.formatters.class = (hasClass, className) => {
  return {
    hasClass,
    className
  }
}
```

with usage being:

```
rv-setclass='model.isActive | class "fooBar"'
```

This feels a bit unwieldy, but it does work.

Did I miss the mark on this? Better option?

**Comment by jccazeaux** [comment]
I don't see any other solution if you want camelCase CSS class names.
In my projects i tell developers to use only lowerCase CSS class names to avoid any problem.

**Comment by MeoMix** [comment]
I've been using CSS Modules, https://github.com/css-modules/css-modules, which encourages the omission of dashes in class names for easier reference of the class in JS.

i.e. styles.isDisabled vs styles['is-disabled']

So it looks like the two desired are at-odds.  Oh well!

**Comment by Duder-onomy** [comment]
@MeoMix Yeah, it is a bummer, binders have to be valid html element attributes. We cannot guarantee casing on the library level. 

Since you are using css-modules, you could always put the class onto the model. 

Something like, `rv-add-class='model.activeClass | when model.isActive'`
Here is a [working fiddle](https://jsfiddle.net/c79vwezg/) for inspiration.

The pertinant bits:

```javascript
var model = {
  activeClass : 'makeLime',
  isActive : true
};

rivets.binders['add-class'] = function(el, value) {
  if((value && !el.rivetsAddedClass) || (value && value !== el.rivetsAddedClass)) {
    el.rivetsAddedClass = value;
  }

  if(value) {
    el.classList.add(value);
  } else if(el.rivetsAddedClass) {
    el.classList.remove(el.rivetsAddedClass);
  }
}

// returns thingA when thingB is true, otherwise returns null.
rivets.formatters['when'] = function(thingA, thingB) {
  if(thingB) {
   	return thingA;
  } else {
    return false;
  }
}
```

```html
<div id='example'>
   <input type='checkbox' rv-checked='model.isActive'>

   <div rv-add-class='model.activeClass | when model.isActive' > </div>
</div>
```

Gonna close this for now. Feel free to reach out if you need anything.
