### ISSUE TITLE
Observer on prototype functions

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#572]
In the fiddle https://jsfiddle.net/jccazeaux/pdfd7tb0/ you will see that the template

```html
{ model.date.getTime }
```
Is not updated when date is changed.
The reason is in the databinding update system. It compares old and new value of expression before updating. In our example, when the date changes, Rivets (actually sightglass) compares the function getTime between old and new `date` value. As `getTime` is a function of Date prototype, it doesn't change when date changes.

See sightglass code here : https://github.com/mikeric/sightglass/blob/master/index.js#L128

(If i must send the issue on sightglass let me know)

**Comment by jccazeaux** [comment]
I finally found a solution for this. 
The `.` adapter creates a new attribute on current obj to register `get` and `set`. During this operation, if `keypath` is a function from `prototype`, the value of the created attribute will a reference to the prototype function. When sightglass tests [value and old value here](https://github.com/mikeric/sightglass/blob/master/index.js#L128) it doesn't see a difference and so doesn't call the `callback`.
The solution is to create a new function instead of referencing the prototype's one when the adapter creates the observed attribute for a prototype function. [You can see implementation here](https://github.com/mikeric/rivets/compare/master...jccazeaux:fix/binding-on-prototypes-functions#diff-426927c556c067ff19879949775c09c7R66)

Tests are OK
Didn't see any regression. PR will follow after more tests.

**Comment by blikblum** [comment]
Instead of creating a copy of function for each object, hence increasing memory usage, i would change sightglass to always call the callback when evaluating functions as i sugestted for arrays.
BTW: this issue will not become a mut point with #582 ?

**Comment by jccazeaux** [comment]
It's not really a copy, more like a wrapper and it concerns only prototype functions. It will have a small memory print.
If functions are always call the callback when evaluating functions we will deteriorate performances because some treatments will be called when not necessary. And this will be done to fix a glitch that concerns only a small amount of functions : prototype functions.

#582 wont solve this problem. In the example described in this issue we will change
```html
{ model.date.getTime }
```
by
```html
{ model.date.getTime | call}
```
The problem will still be there. If `sightglass` does not see the difference in `getTime` function when `date` changes, the expression will not be reevaluated.

**Comment by stalniy** [comment]
I disagree with proposed solution. Basically if date object is changed sightglass should detect this change without additional wraps, otherwise it'll consume a lot of memory in big apps

**Comment by jccazeaux** [comment]
Date change is detected, it's the function change that is not detected. If sightglass see a function it should so always call the callback when evaluating functions as @blikblum said. I must admit i cannot decide which solution will be best. One will have memory impact, the other will have performance impact (potential useless execution)

**Comment by stalniy** [comment]
if `date` is changed the rest of the keypath should be reevaluated in case if path contains function. Another way is to add custom adapter for calling functions.

**Comment by blikblum** [comment]
In my proposed solution there's no performance impact, since will be reevaluated only when date changes. In your proposed solution it will be also evaluated when date changes with the memory usage penalty

**Comment by jccazeaux** [comment]
OK I see your point. Thanks.
So the impact is only on sightglass.

**Comment by jccazeaux** [comment]
PR sent is sightglass https://github.com/mikeric/sightglass/pull/16

**Comment by jccazeaux** [comment]
I just sent a PR to add a test for this issue. This test will pass if https://github.com/mikeric/sightglass/pull/16 is merged and integrated in rivets
