### ISSUE TITLE
[ES6] rivets.bind crashes when executed on jquery Element

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#573]
Try
```javascript
rivets.bind($('#myel)');
```
Rivets crashes here: https://github.com/mikeric/rivets/blob/es6/src/view.js#L116
Error is : `this.els.forEach is not a function`

Cause is here I think : https://github.com/mikeric/rivets/blob/es6/src/view.js#L16

**Comment by blikblum** [comment]
See https://github.com/mikeric/rivets/pull/543

**Comment by jccazeaux** [comment]
Thanks, didn't see it.

**Comment by jccazeaux** [comment]
PR #543 has been merged
