### ISSUE TITLE
unbind data

### ISSUE THREAD

**Issue by junior201110** [mikeric/rivets#588]
How can I make a  correct unbind from my view. I'm already used var view = rivets.bind($('#selectro'),{name:'victor',age:'25'}); and when I want to make a unbind, I use view.unbind(), but this not work.  And I try it  for many times but not work. Maybe I have to make something different. Can you help me?

**Comment by Duder-onomy** [comment]
Hi,

This should do the trick.
```javascript
view.unbind();
```
Can you update my jsfiddle to reproduce your error?
https://jsfiddle.net/Vornagreg/zdumk6t6/

This fiddle will bind a model, then on a interval, it will update the model. You will see the value update in the DOM.  Then, if you click the button, it will unbind the view. You will see the value is no longer updated. 

Can you clarify your question? 

If there is no issue can you close this? Thanks.

**Comment by junior201110** [comment]
Look for what I used to make for to unbind data
https://jsfiddle.net/c15bbqpL/

2016-02-16 19:40 GMT-02:00 Greg Larrenaga <notifications@github.com>:

> Hi,
>
> This should do the trick.
>
> view.unbind();
>
> Can you update my jsfiddle to reproduce your error?
> https://jsfiddle.net/Vornagreg/zdumk6t6/
>
> This fiddle will bind a model, then on a interval, it will update the
> model. You will see the value update in the DOM. Then, if you click the
> button, it will unbind the view. You will see the value is no longer
> updated.
>
> Can you clarify your question?
>
> If there is no issue can you close this? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mikeric/rivets/issues/588#issuecomment-184884943>.
>



-- 
*junior201110>>>*

**Comment by junior201110** [comment]
​​
Oh, tanks for response my issue so fast

2016-02-18 0:02 GMT-02:00 Washington Junior <junior201110@gmail.com>:

> Look for what I used to make for to unbind data
> https://jsfiddle.net/c15bbqpL/
>
> 2016-02-16 19:40 GMT-02:00 Greg Larrenaga <notifications@github.com>:
>
>> Hi,
>>
>> This should do the trick.
>>
>> view.unbind();
>>
>> Can you update my jsfiddle to reproduce your error?
>> https://jsfiddle.net/Vornagreg/zdumk6t6/
>>
>> This fiddle will bind a model, then on a interval, it will update the
>> model. You will see the value update in the DOM. Then, if you click the
>> button, it will unbind the view. You will see the value is no longer
>> updated.
>>
>> Can you clarify your question?
>>
>> If there is no issue can you close this? Thanks.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mikeric/rivets/issues/588#issuecomment-184884943>.
>>
>
>
>
> --
> *junior201110>>>*
>



-- 
*junior201110>>>*

**Comment by Leeds-eBooks** [comment]
Closing this as it appears resolved, I can reopen if not.
