### ISSUE TITLE
Universal forEach for use `each-*` with custom collections

### ISSUE THREAD

**Issue by Riim** [mikeric/rivets#589]
Like that:
```js
var symbolSupported = !!(window.Symbol && Symbol.iterator);

function forEach(collection, cb) {
    // for es6 and custom collections
    if (symbolSupported && collection[Symbol.iterator]) {
        for (var i = 0, iterator = collection[Symbol.iterator](), step; !(step = iterator.next()).done; i++) {
            cb(step.value, i);
        }
    // for arrays and custom collections
    } else if (typeof collection.forEach == 'function') {
        collection.forEach(cb);
    // 
    } else if (isArrayLike(collection)) {
        for (var i = 0, l = collection.length; i < l; i++) {
            cb(collection[i], i)
        }
    } else {
        // for-in
    }
}
```

and use in `binders['each-*']`.

You can even consider https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/values

**Comment by Duder-onomy** [comment]
Hi, 
Rivets uses the adapter pattern to teach rivets how to subscribe to key paths. There should be no reason that rivets core needs to know how to traverse something.

If your custom collection needs to be iterated over in a special way, you could define an adapter that returns a normal array of values from your collection. 

For example, if you had a nodeList and you wanted to iterate on it in a `rv-each-*` you could make an adapter like so:

```javascript
rivets.adapters['%'] = {
    observe: function(model, keypath, callback) {
        // up to you how to observe a nodeList...or even if you want to observe at all.
    },
    unobserve: function(model, keypath, callback) {
        // up to you.
    },
    get: function(nodeList, keypath) {
        return Array.prototype.slice.call(nodeList); // turns into normal array for the each binder
    },
    set: function(model, keypath, value) {
        // up to you.
    }
}
```

You could use this like:
```html
<div rv-each-node='model.nodeList%' ></div>
```

The important thing to note, rivets uses the 'dot' adapter to access the nodeList from the model. Then it will use the % adapter to get the nodeList. 

Does this help you?

**Comment by jccazeaux** [comment]
That's a nice tip, I never thought to use adapters like that, you gave me an idea to solve a problem I have on my projects !

**Comment by Duder-onomy** [comment]
@Riim Can you close this if it helps you? Thanks
