### ISSUE TITLE
Rivets binds binders on component's element twice

### ISSUE THREAD

**Issue by stalniy** [mikeric/rivets#596]
Basically when I want to apply binder to my component element like
```html
<workspace item="workspace" rv-class-editable="workspace.isEditable"></workspace>
```
Then `rv-class-*` binder is bound twice, I mean we have 2 separate views which creates 2 separate bindings for the same attribute (parent's view, and component's view)

That makes problems when attribute name doesn't equal parent's view name as in example (the fix could be to use same name `workspace="workspace` instead of `item=workspace` but this is unclear)

The possible fix could be to bind only `childNodes` inside `ComponentBinding`
```js
this.componentView = new Rivets.View(Array.prototype.slice.call(this.el.childNodes), scope, options);
```

CC: @blikblum @Duder-onomy @Leeds-eBooks

**Comment by stalniy** [comment]
I can create pull request if everybody is happy with the fix

**Comment by Leeds-eBooks** [comment]
I'm probably being stupid but I don't understand this. What do you mean by "attribute name doesn't equal parent's view name"?

**Comment by stalniy** [comment]
@Leeds-eBooks I meant attribute name of the component in the example this is `item` and variable name of the parent view `workspace` are different. If you make them to be same (attribute name `workspace` and parent's variable name `workspace`) then it should work as expected. 

However this is more like "stupid" workaround which doesn't fix double execution of binders and doesn't help in case you use keypath (e.g. `<workspace item="model.workspace"  rv-class-editable="workspace.isEditable"></workspace>`)

Is it clear now what I meant?

**Comment by Leeds-eBooks** [comment]
Are you saying that `rv-class-editable` is passed into the component's internal attributes, rather than just being used by the parent view?

**Comment by stalniy** [comment]
@Leeds-eBooks 
No, I'm saying that `rv-class-editable` is called twice (this is the main issue):
1. by parent view, with parent view models (in the place where `workspace` variable exists)
2. by component view, with component's models (in the place where `workspace variable doesn't exist)

Probably this fiddle can illustrate the problem better than my words =) https://jsfiddle.net/stalniy/c8vnamuh/

**Expected result**:
text inside component is green (`editable` class is added to `workspace` DOM element)

**Actual result**:
text inside component is black (`editable` class is not added to `workspace` DOM element)

**Comment by Leeds-eBooks** [comment]
Ok I understand. Component views should definitely not re-bind binders on the component element in the parent view, I think this is a bug. Your solution seems ok to me.

**Comment by stalniy** [comment]
Done

**Comment by stalniy** [comment]
@Leeds-eBooks do you plan to merge related PR?

**Comment by Leeds-eBooks** [comment]
Yes, sorry, have been really busy recently, had to take on another freelance job so time for Rivets has been 0 recently. I will get to it as soon as I can.
