### ISSUE TITLE
Formatter's publish method receive expressions in arguments and not the appropriate values

### ISSUE THREAD

**Issue by stalniy** [mikeric/rivets#598]
```js
rivets.formatters.contains = {
  read: function(items, item) {
    return items.indexOf(item) !== -1
  },

  publish: function(isChecked, items, item) {
    console.log(arguments); // true, 'item'
  }
};
```

```html
 <input type="checkbox" rv-checked="items | contains item" />
```

Fiddle: https://jsfiddle.net/stalniy/wfnz5dtd/

open console and check output.
**Expected result**:
`[true, 1, []]`

**Actual result**:
`[true, "item", "items"]`

**Comment by milonas115** [comment]
Same issue here. Any update on this? Been 3 months since question asked. Anyone even supporting this project anymore?

**Comment by milonas115** [comment]
Created a work around (For ES6). I am storing the parameters being used on the read method and then using the same parameters + value on the publish method.

**Comment by Leeds-eBooks** [comment]
This will be fixed by https://github.com/mikeric/rivets/pull/655 and is also mentioned in https://github.com/mikeric/rivets/issues/649. Really sorry for the delay.
