### ISSUE TITLE
Nested `rv-if` issue

### ISSUE THREAD

**Issue by stalniy** [mikeric/rivets#603]
**Steps to reproduce**:
1. Create 2 nested `rv-if` elements
2. Change the boolean value of the first `rv-if` to `false` (`boolean1` in example)
3. Change some model value of nested `rv-if` (`name` in example inside text input)
4. Change the changed boolean value back to `true` (`boolean1` in example)

**Actual result**:
The wrong value is shown inside nested `rv-if` (bindings are not updated and the old `name` is shown)

**Example**: https://jsfiddle.net/stalniy/958u43h3/

**Comment by stalniy** [comment]
CC: @blikblum @Leeds-eBooks @Duder-onomy @jccazeaux

**Comment by Duder-onomy** [comment]
This is sort of expected. Though, should be fixed at some point. There are MANY issues open right now that have this same problem and can be simply fixed.

You must always wrap the bound items in a object. 

See this fiddle working fine with nested `rv-if` https://jsfiddle.net/ad37yp6t/

**Comment by stalniy** [comment]
@Duder-onomy your fiddle doesn't work as expected. The issue is not in the object!

Click boolean1 (unchecked) then change input value and click boolean1 once more (checked). 

First name is updated and name in the second rv-if is not!

Reopen this please
