### ISSUE TITLE
Are nested scopes possible?

### ISSUE THREAD

**Issue by delicious-roasted-turkey** [mikeric/rivets#606]
I've not found any reference to nested scopes in the documentation. Are they supposed to work? Something like:

```js
var outercontext = {};
var innercontext = {};

rivets.bind($("#outer"), outercontext); // (1)
rivets.bind($("#inner"), innercontext); // (2)

outercontext.foo = "Foo"

```

```html
<div id="outer">

  Value of foo is: {foo}

  <div id="inner">

    Value of foo is: {foo}
  
  </div>

</div>
```
Right now, it seems that the result depends on the order of lines `(1)` and `(2)` (see [this fiddle](https://jsfiddle.net/_abl/4zbrutjs/1/) and [this one](https://jsfiddle.net/_abl/h9ytbkn6/2/)).

**Comment by tanshul22** [comment]
Nested scopes work but the way you're approaching it is illegal. When you bind to an element, all sub-elements get bound too. You can't bind your sub-elements again as they are already bound to your initial binding. If you dynamically inject DOM elements after the initial binding, you new elements can and will need to be bound separately.

A better approach to solving your problem would be to set values on the context already bound. See updated JSFiddle below.

[https://jsfiddle.net/4zbrutjs/2/](https://jsfiddle.net/4zbrutjs/2/)

Hope this helps!

**Comment by Leeds-eBooks** [comment]
Closing, please comment if your issue is not fixed.
