### ISSUE TITLE
problems with rivets.bundled.min and gulp

### ISSUE THREAD

**Issue by johnny-carmona** [mikeric/rivets#609]
Hi,

I'm trying to use this library on a project where the build is done using gulp, but even though I'm using the bundle version I'm getting the following error:
[15:06:05] gulp-notify: [[browserify] Compile Error] Cannot find module 'sightgl
ass' from 'C:\Users\Johnny Carmona\Documents\projects\UIG\dls-framework\src\scri
pts\mck-ui\lib'
Regards,

Johnny

**Comment by Duder-onomy** [comment]
Hi Johnny, 
Did you install with bower or npm?

Rivets has a dependency on a library called [`sightglass`](https://github.com/mikeric/sightglass). 

In the rivets `dist` directory there are 3 versions. You will probably want to use the bundled version, OR, you need to ensure that rivets is shimmed with [`sightglass`](https://github.com/mikeric/sightglass). 

Looks like you are using browserify, so I recommend using the NPM version. I have never had problems with that version. 

Let me know where you get.

**Comment by johnny-carmona** [comment]
Hi,

I downloaded the bundled version, also tried with bower install and still
had the same issue.
I managed to make it work after changing a few lines in the code.
btw I'm trying to use this so I can have static templates on handle bars
and just use doble side binding, is there a way I can set a class on an
element like this:
<span class="icon_{ item.icon}">{ item.text }</span> or like this <span
rv-class="icon_{ item.icon}">{ item.text }</span>

Regards,

Johnny

**Comment by Duder-onomy** [comment]
Hi Johnny,

You will def want a custom binder. 
This one is a classic. I think everyone has this in their rivets projects.

`rv-add-class='item.icon'`


```javascript
// make sure you do this before rivets.bind
rivets.binders['add-class'] = function(el, value) {
    el.classList.add(value);
}
```

That should do it for you.

**Comment by Leeds-eBooks** [comment]
Closing, please comment if your issue is not fixed.
