### ISSUE TITLE
Nested rv-if don't rebind correctly

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#611]
Hi all

I recently encountered this issues : 
Consider this DOM 
```html
  <div rv-if="scope.firstDiv">
    <div rv-if="scope.secondDiv">
      <input rv-value='scope.data2'>{ scope.data2 }
    </div>
  </div>
```
If `scope.firstDiv` is set to `false` then `true` the `secondDiv` if correctly shwon but databinding is lost.
You can test it there : https://jsfiddle.net/jccazeaux/ou483fdj/
As you can see, databinding is lost when we toggle the level 1. To activate the databinding again we have to toggle the level 2.

This is a glitch in `rv-if` binder which doesn't reinit a `bound` flag. PR will follow

**Comment by jccazeaux** [comment]
That was fast :smile:

**Comment by Leeds-eBooks** [comment]
:) I'm trying to get back on top of things. Do you think we're ready for a new version, and if so, do you know how we go about it?

**Comment by jccazeaux** [comment]
I think we're ready for a `0.9`. There was many updates since `0.8.1` and it's worth a release.
I don't think we leave important issues behind for now. I know there is still work on components but it can wait for a next release. 
How we go about it? Well I don't really know. First we must synthetize all PR for the release notes (already done in issue #560) . Then build and go.

**Comment by Leeds-eBooks** [comment]
Ok, could you add your recent PRs to the list in #560? Then I will look into how we push a new version.

**Comment by jccazeaux** [comment]
Done. I'll take some time to make sure no PR was missed.
