### ISSUE TITLE
rv-if / rv-show using unclear definition of true/false

### ISSUE THREAD

**Issue by jiaweihli** [mikeric/rivets#614]
These binders (and their opposites: `rv-unless`, `rv-hide`) use `if (x)` to do a truthy test:
https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L120

But that doesn't check for truthiness - it actually checks for the existence of the object.  This is described in more detail in this [SO post](https://stackoverflow.com/questions/5491605/empty-arrays-seem-to-equal-true-and-false-at-the-same-time).  An interesting backstory can be found [here](http://www.2ality.com/2013/08/objects-truthy.html).

![screen shot 2016-04-25 at 2 50 34 pm](https://cloud.githubusercontent.com/assets/351887/14800226/25edad7a-0af5-11e6-8828-7b067e2b29f5.png)

Right now these binders don't work correctly with empty array, which is still an object and evaluates to true.  This means that a variable holding an array can never trigger `rv-hide`/`rv-unless`.

I'd expect empty array to evaluate to false (this is the wording used [in the docs](http://rivetsjs.com/docs/reference/#if)).  

This can be done by using a `x == false` check instead of the current `if (x)` check.
Alternatively, the documentation can be updated with clearer wording (e.g. falsy values) or a list of values that will trigger the binders.
Happy to submit a PR for this if it sounds reasonable.

**Comment by Leeds-eBooks** [comment]
Personally I think this is a documentation issue – it makes sense to me that this works the same way as JavaScript `if`. If you want to check for empty arrays, you should write your own formatter that returns the Boolean value you expect to the `rv-if` binder. Something like:

```javascript
rivets.formatters.isNotEmpty = function(arr) {
  return Array.isArray(arr) && arr.length > 0
}
```
```html
<... rv-if="arr | isNotEmpty">
```

**Comment by jiaweihli** [comment]
Sounds good - then I'll submit a PR that updates the wording to 'falsy values'?

The point I want to stress is that 'falsy values' means something different from 'evaluates to false'.

**Comment by Duder-onomy** [comment]
This one is interesting. Would love to see the PR update the docs. 
But that is simply how JS works. Coercion is a very important part of the language. I could just as easily see someone making a bug report saying : 
'Javascript will coerce an empty array to true, but my element is still hidden'

So I agree with @Leeds-eBooks we should just make sure the docs detail that this is using standard javascript coercion.

**Comment by Leeds-eBooks** [comment]
So a PR would be welcome!
