### ISSUE TITLE
How can I add a class on false condition?

### ISSUE THREAD

**Issue by snify** [mikeric/rivets#615]
I have the following code:

`<button rv-on-click="app.togglePlay" rv-class-playing="app.isPlaying | eq true" rv-class-not-playing="app.isPlaying | eq false">Play/Pause</button>`

I'm trying to trigger a class if app.isPlaying is true and another class if it's false.
How can I do this with Rivets?

**Comment by Leeds-eBooks** [comment]
Is the above not working?

**Comment by Leeds-eBooks** [comment]
An alternative would be:
```html
<button rv-on-click="app.togglePlay" rv-class-playing="app.isPlaying" rv-class-not-playing="app.isPlaying | not">
  Play/Pause
</button>
```

```js
rivets.formatters.not = function(x) {
  return !x
}
```

**Comment by Leeds-eBooks** [comment]
Closing this for now, please say if this is not resolved.
