### ISSUE TITLE
nested if binder not re-evaluating nodes

### ISSUE THREAD

**Issue by tanshul22** [mikeric/rivets#618]
Notice in the JSFiddle below how the if binder retains an old state of its child elements upon unbinding and doesn't re-calculate the child element when bound again. I understand this is because the observable on the if binding itself isn't changing but one would expect it to re-evaluate the children upon binding again regardless.

[https://jsfiddle.net/rpefhkhg/](https://jsfiddle.net/rpefhkhg/)

I have a proposed re-write of the if binder with forceful unbinds and bind on its children. This in my opinion is an in-efficient solution and I'm hoping the authors may have a slightly graceful approach to this problem. Adding it below. Notice inline comments to see the changes.

```
Rivets["public"].binders["if"] = {
    block: true,
    priority: 4000,
    bind: function(el) {
      var attr, declaration;
      this.bound = null; // Set to null
      if (this.marker == null) {
        attr = [this.view.prefix, this.type].join('-').replace('--', '-');
        declaration = el.getAttribute(attr);
        this.marker = document.createComment(" rivets: " + this.type + " " + declaration + " ");
        this.bound = null; // Set to null
        el.removeAttribute(attr);
        el.parentNode.insertBefore(this.marker, el);
        return el.parentNode.removeChild(el);
      }
    },
    unbind: function() {
      var _ref1;
      this.bound = null; // Set to null
      return (_ref1 = this.nested) != null ? _ref1.unbind() : void 0;
    },
    routine: function(el, value) {
      var key, model, models, _ref1;
      if (!!value === !this.bound || this.bound === null) {
        if (value) {
          models = {};
          _ref1 = this.view.models;
          for (key in _ref1) {
            model = _ref1[key];
            models[key] = model;
          }
          (this.nested || (this.nested = new Rivets.View(el, models, this.view.options()))).bind();
          this.marker.parentNode.insertBefore(el, this.marker.nextSibling);
          return this.bound = true;
        } else if(el.parentNode != null) { // Parent may be missing
            this.nested.unbind(); // Unbind before moving child
            el.parentNode.removeChild(el);
          return this.bound = false;
        }
      }
    },
    update: function(models) {
      var _ref1;
      return (_ref1 = this.nested) != null ? _ref1.update(models) : void 0;
    }
  };
```

**Comment by tanshul22** [comment]
I have an updated JSFiddle with a much thorough and improved JS fix. The link below demonstrates all problem cases I've encountered.

[https://jsfiddle.net/cvo4qomt/](https://jsfiddle.net/cvo4qomt/)

```
    // ak: Fix for issue #618 - if binders need their view to be built again
    View.prototype.rebind = function() {
      var binding, _i, _len, _ref1, _results;
      _ref1 = this.bindings;
      _results = [];
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        binding = _ref1[_i];
        if(binding.type === "if"){
            _results.push(this.build());
            _results.push(this.bind());
        }else{
            _results.push(binding.bind());
        }
      }
      return _results;
    };

    // ak: Fix for issue #618 - replace element text with original token
    TextBinding.prototype.unbind = function() {
      var delimiters, _results;
      delimiters = this.view.templateDelimiters;  
      _results = TextBinding.__super__.unbind.apply(this, arguments);
      this.el.textContent = delimiters[0] + this.keypath + delimiters[1];
      return _results;
    };

    // ak: Fix for issue #616 - sync after updating models
    TextBinding.prototype.update = function() {
      var _results = [];
      _results.push(TextBinding.__super__.update.apply(this, arguments));
      _results.push(TextBinding.__super__.sync.apply(this, arguments));
      return _results;
    };

```

The routine for rv-if needs to be changed as follows:

```
-          (this.nested || (this.nested = new Rivets.View(el, models, this.view.options()))).bind();
+          // ak: Fix for issue #618 - nested if content needs to be re-bound
+          if(this.nested){
+            this.nested.rebind();
+          }else{
+            this.nested = new Rivets.View(el, models, this.view.options());
+            this.nested.bind();
+          }

```

**Comment by jccazeaux** [comment]
Hi @tanshul22 , is it a duplicate of #611 ?

**Comment by tanshul22** [comment]
Hi @jccazeaux, I tried setting ```bound``` to ```false``` (and to ```null``` as in first comment above) for starters and it does seem to solve some basic problems but I have an extremely large and complex application with multiple nested ```if``` binders and setting ```bound``` to ```false``` doesn't seem to solve all my issues. I've updated the second comment above with all my latest changes. Some of these may be workarounds as I'm still learning the source code. My fixes do seem to work though.

1. Notice how ```TextBinding.unbind``` needs to re-create the original text content. I believe my solution may be the right solution.
2. As you'll notice, unbinding an ```if``` or ```unless``` needs to unbind all nested views as well. I'm guessing there may be a better way to do this but this seemed extremely necessary.
3. As you'll notice, I've introduced a ```View.rebind```. This may seem hacky and it very well might be. I couldn't figure out another graceful way to solve this. But just like ```unbind```, it seems very necessary that ```if``` and ```unless``` binders traverse their nestings during a ```rebind```.

**Comment by tanshul22** [comment]
@jccazeaux, I believe your fix for #611 does seem to be working and definitely seems like a much better fix than my ```rebind``` function. It does seem like my implementation of ```TestBinding.unbind``` is still necessary which is what was originally throwing me off. Maybe its worthwhile to split this up into its own bug. Adding code snippet below for easy access.

```
    // ak: Fix for issue #618 - replace element text with original token
    TextBinding.prototype.unbind = function() {
      var _ref1, _ref2, _ref3, _results;
      _ref1 = this.view.templateDelimiters;
      _ref2 = this.options.dependencies ? ' < ' + this.options.dependencies.join(' ') : '';
      _ref3 = this.options.formatters.length ? ' | ' + this.options.formatters.join(' | ') : '';
      _results = TextBinding.__super__.unbind.apply(this, arguments);
      this.el.textContent = _ref1[0] + this.keypath + _ref2 + _ref3 + _ref1[1];
      return _results;
    };
```

**Comment by jccazeaux** [comment]
Why would it be necessary to reset text content with original template code? Unbind's role is to shut down observers, not to reset template code. Am I missing something?

**Comment by tanshul22** [comment]
Please take a look at the following fiddle. How would you propose one go about resetting the `TextBinding` template in this case? Maybe `TextBinding.unbind` isn't the correct function for such an operation but resetting the `TextBinding` template seems necessary in this case.

[https://jsfiddle.net/havessex/1/](https://jsfiddle.net/havessex/1/)

**Comment by tanshul22** [comment]
Closing this issue as its considered a duplicate of #611. Opened #623 to address the issue with `TextBinding`.
