### ISSUE TITLE
buildBinding regex breaks with multiple strings

### ISSUE THREAD

**Issue by agmonks** [mikeric/rivets#620]
This is broken in 0.9 (fixed as part of #432)

`/((?:'[^']*')*(?:(?:[^\|']+(?:'[^']*')*[^\|']*)+|[^\|]+))|^$/g` 

This breaks for the following example (not picking up the 2nd string):

`receiptTypeId | lookup reciptTypes 'value' 'key' `

I'm trying to come up with a working regex but I'm not great at regex!

**Comment by jccazeaux** [comment]
Damn, didn't see that 😞 
I found a better regexp. It works fine but returns empty strings. Didn't find a way to eliminate these in the regexp. So i eliminated them with a `filter`. PR will follow, if anyone has a better idea i'll happy to see it !

**Comment by agmonks** [comment]
I came up with the same regex issues with the empty spaces. Would recommend not using filter as for loop would work quicker (don't think the extra checks filter runs are needed here)

**Comment by jccazeaux** [comment]
I agree, the code is work in progress. I hoped someone could help to find THE regexp ;-)
In the meantime feel free to propose a better/faster solution.

**Comment by agmonks** [comment]
How about:

`((?:'[^']*')*(?:(?:[^\|']*(?:'[^']*')+[^\|']*)+|[^\|]+))|^$`

**Comment by jccazeaux** [comment]
Looks great!
I'll close m'y PR, feel free to send a PR with your solution (won't be able to do it until 2 weeks)

**Comment by agmonks** [comment]
@Leeds-eBooks This issues probably justifies a 0.9.1 release (as it might break other peoples apps like mine)?

**Comment by Leeds-eBooks** [comment]
`0.9.1` published!

**Comment by agmonks** [comment]
Excellent! Thanks

**Comment by agmonks** [comment]
@Leeds-eBooks  FYI I have also created a ES6 fix (PR #626) as well (also had to fix up the testing framework in PR #625)

**Comment by jccazeaux** [comment]
Great ! Thanks !
