### ISSUE TITLE
Travis CI, Updated Webpack & Babel

### ISSUE THREAD

**Issue by agmonks** [mikeric/rivets#628]
I've created a PR (#277), Done a fair bit of work in getting webpack upto date and also creating a travis build that works (https://travis-ci.org/agmonks/rivets/builds/).

Hopefully this can help bring v1 forward. all feedback / suggestions welcome.

**Comment by agmonks** [comment]
https://travis-ci.org/agmonks/rivets/builds/

**Comment by Leeds-eBooks** [comment]
Merged!
