### ISSUE TITLE
Reset Form

### ISSUE THREAD

**Issue by DangerStu** [mikeric/rivets#629]
What's the best way to handle a standard form reset. i.e. I have both a span bound to rv-text="data.ContactVM.JobTitle" and a input filed bound to rv-value="data.ContactVM.JobTitle"

Hitting a reset button resets the the input fields but the values don't propagate to the spans.

Thanks
Stuart

**Comment by jccazeaux** [comment]
The `reset` function on forms does not fire any event on inputs so rivets will not be aware that the input values have changed. DataBinding is not working here. 
As a workaround you can listen to the `reset` on your form and reinit the values of your model
```
<form rv-on-reset="data.reset">
[...]
</form>
```
Where resetMyData will look like
```javascript
data.reset = function() {
   this.ContactVM.JobTitle = null;
   [...]
}
```

**Comment by DangerStu** [comment]
Thanks!

**Comment by Leeds-eBooks** [comment]
Closing, please comment if your issue is not fixed.
