### ISSUE TITLE
How to loop over definition list items (dl)

### ISSUE THREAD

**Issue by mkastner** [mikeric/rivets#631]
How would I loop over definition list items?

`            <dl>
                    <dt></dt>
                    <dd></dd>
            </dl>`

Binding to rv-each to dl-element would repeat the dl element itself and binding to dt would only loop over dt.

Guess, I would have to write a custom binder for that or is there a better solution?

**Comment by Leeds-eBooks** [comment]
Is it unsemantic to use divs to wrap each pair?

**Comment by mkastner** [comment]
Yep, that's what the specification says. I've turned it into a list now, so I can loop over the li-element.

**Comment by stereonom** [comment]
Having the same problem. Have anyone figured out a good way?
