### ISSUE TITLE
Tips on how to use with JSPM / SystemJS?

### ISSUE THREAD

**Issue by justinmetros** [mikeric/rivets#632]
Hey Everyone!

Good to see a lot of action here, we use Rivets on many projects, thanks for all your hard work!

Recently moved over to JSPM / SystemJS and can't for the life of me get this to work properly. Tried shimming, specifying exports, loading from npm with deps, from github and importing sightglass separate, [ everything under the sun ]( https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm ).

Works great if I just load it in its own script tag, but would be nice to have it all together in my builds. This is the only package I seem to have trouble with, so I figure I must be doing something wrong. Tried to read all the open & closed issues before posting but didn't really see anything specific to my issue.

Any insight greatly appreciated! Thanks in advance!

**Comment by justinmetros** [comment]
To add some additional info. I can `import rivets from 'rivets'` and `console.log( rivets )` returns as expected, but anything i try to use invokes an error. e.g. `rivets.configure({ ... })` spits out a `rivets is undefined` error. Very odd. I'm sure its not a bug, just maybe incompatible. Again any insight would be awesome, thanks in advance!

**Comment by Leeds-eBooks** [comment]
What does `console.log(rivets)` actually print to the console?

**Comment by justinmetros** [comment]
Exactly what one would expect. A rivets object with all of its properties and methods. Yet, when i try access any of them it returns rivets undefined.

Given systemjs and jspm are quite new, i feel like its some minor incompatability. Ive specicifed cjs format but no go. Use dozens of tools across projects, cjs, amd, globals... This is the only package i have a trouble with, particularly frustrating personally because i love it so much. 

A wiser man could be more specific identifying the issue. I will try and put together the most basic example possible in effort to illustrate. I wouldnt expect anyone to have an answer unless they have had direct experience with rivets in sustemjs, because it works great everywhere else. Its just... odd. All things point to it working but it doesnt.

**Comment by Leeds-eBooks** [comment]
My next step would be to assign rivets to `window.rivets` and then try executing it in the console, see if you get a more useful error message.

**Comment by nomiad** [comment]
I have to shim it currently. I install it over Bower:
`
meta:{
    "bower:rivets@0.8.1/dist/rivets.js": {
      "globals": {
        "sightglass": "bower:sightglass@0.2.4"
      }
    },
  },
  map: {
    "rivets": "bower:rivets@0.8.1",
    "bower:rivets@0.8.1": {
      "sightglass": "bower:sightglass@0.2.4"
    }
  }
`

With this it works quite fine

**Comment by nomiad** [comment]
For 0.9 I've now written an override to install
`jspm install rivets=github:mikeric/rivets -o "{ 'shim':{'dist/rivets.js':{'sightglass':'mikeric/sightglass@0.2.4'} },'dependencies': { 'sightglass': 'mikeric/sightglass@0.2.4'} }"`

I'll will write an pullrequest for the registery

**Comment by Leeds-eBooks** [comment]
I'm not sure if this is fixed or not but I'm closing for now, please reopen if you're still having issues.

**Comment by justinmetros** [comment]
The above override worked perfect! Thank you!
