### ISSUE TITLE
read method for default adapter

### ISSUE THREAD

**Issue by mkastner** [mikeric/rivets#633]
In the documentation about the binder there is a example for a toggle binder which uses an adapter.

[http://rivetsjs.com/docs/guide/#binders]

Now, if i am using plain JSON objects, would there also be a read method available, in order to access the value at the respective keypath?

**Comment by mkastner** [comment]
To be more specific: how would I do this:

`  bind: function(el) {
    adapter = this.config.adapters[this.key.interface]
    model = this.model
    keypath = this.keypath

    this.callback = function() {
      value = adapter.read(model, keypath)
      adapter.publish(model, keypath, !value)
    }

    $(el).on('click', this.callback)
  }`


but with the default adapter?

This does not work (I am explicitly calling the default adapter by its key '.'):

`  bind: function(el) {
    defaultAdapter = this.config.adapters['.']
    model = this.model
    keypath = this.keypath

    this.callback = function() {
      value = defaultAdapter.read(model, keypath)
      defaultAdapter.publish(model, keypath, !value)
    }

    $(el).on('click', this.callback)
  }`

How else can it be done?

**Comment by mkastner** [comment]
Ok, I've come this far:

`rivets.binders.toggle = {

  	bind: function(el) {

    	var model = this.model;
    	var keypath = this.keypath;
    	var adapter = rivets.adapters['.'];

    	var that = this;

	    this.callback = function() {

	    	var value = adapter.get(model, keypath);

	    	// There is no read method!!!
	    	
	    	var newValue = !value;

	    	// adapter does not have a publish method!!!

	      	that.publish(model, keypath, newValue);		    	


	    };

	    el.addEventListener('click', this.callback);

  	},

  	unbind: function(el, value) {

  		el.removeEventListener('click', this.callback);

  	},

  	routine: function(el, value) {

  		value ? el.classList.add('enabled') : el.classList.remove('enabled');
  	
  	}
};`

**Comment by agmonks** [comment]
same as #634 , use self.observer to get and set the values.
