### ISSUE TITLE
Update with custom binder not working

### ISSUE THREAD

**Issue by mkastner** [mikeric/rivets#634]
I am trying to get a custom binder (quite similiar to the documentation example) going, but it's not changing the model and it's not calling routine. Please, if someone could help me with this:

[http://jsfiddle.net/mtkastner/v5mtp3jo/](http://jsfiddle.net/mtkastner/v5mtp3jo/)

**Comment by mkastner** [comment]
Here's an even simpler fiddle. It looks like there's a problem (or I simply don't get it) with the default keypath interface. The values are simply not set nor are they being returned by the respective keypath.

I apologize for cluttering the issues section, but I really don't know where else to turn to:

[https://jsfiddle.net/mtkastner/bu4844dd/](https://jsfiddle.net/mtkastner/bu4844dd/)

**Comment by agmonks** [comment]
https://jsfiddle.net/bu4844dd/8/

use self.observer to get and set the values

**Comment by mkastner** [comment]
Thank you very much. From what I understood from the documentation, and obviously I misunderstood or misinterpreted, I thought one would have to register at least the '.' adapter.

I don't know if I am the only one taking the wrong turns, but it might be helpful if an example like this would be mentioned in the documentation.

Anyway, again, thank you very much.

**Comment by agmonks** [comment]
yes the documentation seems quite out of date, really needs refreshing
