### ISSUE TITLE
on-event binder doesn't call function of backbone model resulting in " this.call is not a function" error

### ISSUE THREAD

**Issue by kospol** [mikeric/rivets#636]
This is a very simple example https://jsfiddle.net/kospol/L3gejff7/10/ with a basic backbone model.
The model uses a two way binder with the view. The button at the view has a "rv-on-click" binder that is supposed to call the "model:testFunc" function but when clicked it results in a "Uncaught TypeError: this.call is not a function" error message.

I'm using rivets version 0.9.0.
The walkaround I found is to use backbone's eventing system to listen for the button's click.

**Comment by jccazeaux** [comment]
I don'k know well BackBone but it seems the `get `method does not retrieve functions, only attributes. IMHO the `:` adapter should only be used for attributes, not for functions. In your test, the `rv-on-click` should be used like this
```html
<button rv-on-click="model.testFunc">Button</button>
```

**Comment by kospol** [comment]
That works, thanks!
