### ISSUE TITLE
Integrating with 3rd party calendar

### ISSUE THREAD

**Issue by greginns** [mikeric/rivets#637]
I'm quite confused trying to implement a binding for a 3rd party calendar widget.
Basically, once a date is chosen in the widget (onSet) how do I get that value into contact.dob?

```html
<input type="text" rv-mobi-calendar='contact.dob'>
```

```javascript
rivets.binders['mobi-calendar'] = {
	bind: function(el) {
        var self = this;
		var keypath = this.keypath;  //contact.dob
		var opts = {};
		opts.onSet = function(text, inst){
			console.log(inst.getVal())   //Wed Jun 29 2016 00:00:00 GMT-0300 (ADT)
            // how to get this back to my model?
		};

		mobiscroll.calendar(el, opts);  // instantiate mobiscroll calendar
	},

	unbind: function(el) {
	},

	routine: function(el, value) {
           // what goes in here?
	},

	publishes: true,
};
```

**Comment by Duder-onomy** [comment]
@greginns Here is what your going to want to do, I hope this makes sense. 

Here is a jsfiddle with some notes in it: https://jsfiddle.net/Vornagreg/yq9x0qxx/

The pertinent bits: 
Your `bind` function will setup the state of the binding. So, in the bind function of your example I have instantiated the 'mobiscroll' library and saved it to the closure as `mobiScrollInstance`
Also, i set the `onSet` callback of the mobiScrollInstance to call the `publish` method of the binding. 

```javascript
bind: function(el) {
        var opts = {};
        opts.onSet = this.publish;

        this.mobiScrollInstance = mobiscroll.calendar(el, opts);  // instantiate mobiscroll calendar
}
```

So, the important part is that the `publish` method of the binding will be called. 
The `publish` method calls `getValue`: https://github.com/mikeric/rivets/blob/master/src/bindings.coffee#L109
The `getValue` method looks at your binding instance and will call another `getValue` method if that is available on your binding instance: https://github.com/mikeric/rivets/blob/master/src/bindings.coffee#L155

So, and here is the cool part, you define a `getValue` method on your binding instance, this will be called when the binder wants to set the value on your model, in the fiddle above, your `getValue` method will look like so:

```javascript
getValue : function(el) {
     return this.mobilScrollInstance.getValue();    
}
```

If you can get the `mobiscroll` lib working in jsfiddle, then I will totally help you implement this binder.

let us know how it goes!

**Comment by greginns** [comment]
That was what I needed.  Excellent, thanks very much!   I never would have figured it out on my own.  It works perfectly, keeps the date in getTime() format, and displays it properly.

My final binder looks like this:

```javascript
rivets.binders['mobi-calendar'] = {
	bind: function(el) {
        var opts = {};
        opts.onSet = this.publish;

        this.mobiScrollInstance = mobiscroll.calendar(el, opts);
	},

	unbind: function(el) {
		this.mobiScrollInstance.destroy();
	},

	routine: function(el, value) {
		if (value) {
			this.mobiScrollInstance.setVal(new Date(value), true);	
		}
	},

	getValue : function(el) {
    	return new Date(this.mobiScrollInstance.getVal()).getTime();    
	},
};
```

**Comment by jccazeaux** [comment]
I didn't know the `getValue` function on binders. It should be added to the docs. It's very interesting !
