### ISSUE TITLE
Computed properties emit function definition instead of function output since Rivets 0.9x

### ISSUE THREAD

**Issue by chris-heijdens** [mikeric/rivets#638]
Computed properties no longer appear to be working as described in the guide since Rivets 0.9.0.

Instead of emitting the result of the function it emits the function itself.

See https://jsfiddle.net/cheijdens/64ta6qzz/

**Comment by aiphee** [comment]
You have to call.
https://jsfiddle.net/64ta6qzz/17/

**Comment by pppdns** [comment]
adding ` | call` worked for me too, I already wasted a few hours on this, thanks @aiphee

**Comment by jccazeaux** [comment]
Yes it's a new feature from `0.9`. You may go back to `0.8` behaviour in the configuration (it will appear in docs when it's updated)
```javascript
rivets.configure({
    // Since rivets 0.9 functions are not automatically executed in expressions. If you need backward compatibilty, set this parameter to true
    executeFunctions: true
});
```

**Comment by goose2460** [comment]
This only works for me if I pipe to call first and then depend on the computed property.  The reverse does not recompute

`obj.computed | call < prop`

**Comment by Leeds-eBooks** [comment]
Hi everyone, sorry about the failure to update documentation. As one of the few people with push access to rivets, I hold my hands up. I am trying to get everything flowing well again around here. We will do better! Thanks almost entirely to the hard work of @jccazeaux, @blikblum, @stalniy, @agmonks and others, docs now explain these new features / breaking changes, and the [changelog](https://github.com/mikeric/rivets/blob/master/CHANGELOG.md) now explains how to upgrade from `0.8`.

@goose2460 could you elaborate a bit more on your issue?

**Comment by goose2460** [comment]
@Leeds-eBooks I can't reproduce it outside of my code base, but for some reason the value is only recomputing when I use this order:

`obj.computed | call < prop`

The reverse:

`obj.computed < prop | call`

does not work.  I'll open an issue if I can reproduce with a simpler example.

**Comment by Leeds-eBooks** [comment]
Thanks, this does sound like a legit bug so if you could make up a simple repro that would be a massive help.

**Comment by goose2460** [comment]
Was able to reproduce when using a formatter.  https://github.com/mikeric/rivets/issues/658
