### ISSUE TITLE
Disable binding to incomplete (or HTML) selectors

### ISSUE THREAD

**Issue by hellodaniel** [mikeric/rivets#642]
We've run into an issue when binding to HTML that may have the selector present in a partial format. 

e.g.: When rendering HTML that contains our selector (```{```) output that should be like this:

	.sample { 
		{somedata}
	}
	
...Rivets, understandably, renders this (with the first curly bracket instance missing):

	.sample 
		The Data
	}
	

We've also tried this:
	
	.sample &#123;
		{somedata}
	&#126;

...but the results are the same (i.e.: rivets even parses HTML versions of the binder).

Aside from changing the selector to, for example, ```{{``` is there  a way to output copy without it being parsed? I know it's a bit of an odd circumstance but I've struggled for a while to find a solution...

**Comment by jamespsterling** [comment]
I'm having the same issue with &nbsp; being parsed and escaped.

**Comment by Duder-onomy** [comment]
Not sure if this is going to help you. But the `{ someThing }` syntax uses the `rv-text` binding under the hood. Could you not just make your own binder? Something like, `rv-unescaped-text`

Here is a jsfiddle I made, Can you fork it and use it to demonstrate your issue: https://jsfiddle.net/Vornagreg/vv1rg83s/

**Comment by hellodaniel** [comment]
Here's a fork of the issue I'm trying to solve (example 3 - example 2 is what I thought would be a fix): https://jsfiddle.net/hv3c1rzw/1/

The solution, really, is to use a different selector. Trouble is we were along way into the project before realising this would be an issue.  It would be useful to have a way to declare exceptions (either via class, ID, or something) or declare multiple-line selectors not parse, or something like that. but, for now, modifying the project's selectors seems like the logical solution.

**Comment by hellodaniel** [comment]
@jamespsterling's issue is a little different to what I'm trying to demonstrate. 

Happy to have this closed, or perhaps marked as a suggestion, with the comment "yeah, nah, we're not gonna do that".

**Comment by jamespsterling** [comment]
@hellodaniel That's the exact issue, the &nbsp; is being parsed into, 

```html
<div>
    Using The Text Binding: <span rv-text="model.information">&amp;nbsp;</span>
</div>
```

This happens whether you do rv-text or just `{ model.information }`

**Comment by jamespsterling** [comment]
@hellodaniel Here's that 2nd example with &ampnbsp;

https://jsfiddle.net/2qr0q7hq/

doesn't seem to solve it any way. 

In the end I found a workaround in the CSS with empty <dd></dd> tags

**Comment by Duder-onomy** [comment]
@jamespsterling and @hellodaniel  Did you know that you could do this: https://jsfiddle.net/Vornagreg/svwnz8uw/

You can change the delimiters that the tempting uses. 

Like so: 
```javascript
rivets.configure({
  templateDelimiters : ['{{', '}}']
});
```

That should help you, no?  (if your proj is already super far along...it might just be annoying to fix everything. ... but life is suffering. and suffering is the path to the dark side. So.... ya know. )

**Comment by jamespsterling** [comment]
@Duder-onomy Still doesn't output the nbsp as a proper html entity...

**Comment by Duder-onomy** [comment]
Ahh, I understand the issue now. you WANT the char code to show up as a space. Aight. Aight. Let get back you you.

**Comment by Duder-onomy** [comment]
Word. So, the text binding works like so: https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L4

Using `textContent` and `innerText` to set the contents of the bound element. This will not parse the html entities. You could use the `rv-html` binding, but that will not work with the template delimiter syntax. 

So, here is a fiddle piping that through a 2 way formatter. https://jsfiddle.net/Vornagreg/svwnz8uw/

I would recommend something like so: (i used a repo called [`he`](https://github.com/mathiasbynens/he) for the encode and decode. Lodash has some nice ones but only supports 6 of the most popular ones: [annotated source](http://underscorejs.org/docs/underscore.html#section-160)

Anyhow, here is a 2 way formatter, will represent the decoded string to the binding, and will represent the string encoded on your bound model. 
```javascript
rivets.formatters.htmlEntity = {
	read : function(stringWithEntities) {
  	return he.decode(stringWithEntities);
  },
  publish : function(stringWithEntities) {
  	return he.encode(stringWithEntities);
  }
}
```

Let me know if there is anything else we can do for you? Or close this please. 

Making the text binding encode and decode html entities will probably not happen. (unless some of the other more important core people here wana chime in. I am mostly just a lurker)

**Comment by jamespsterling** [comment]
@Duder-onomy Perfect solution, thank you so much!

**Comment by Duder-onomy** [comment]
Awesome! Im gonna close this.

**Comment by jamespsterling** [comment]
Update, I found a simpler entity decoder if anyone else has this issue and is looking for somrthing more lightweight. he.js is huge (~59kb minified). 

```js
var decodeEntities = (function () {
    //create a new html document (doesn't execute script tags in child elements)
    var doc = document.implementation.createHTMLDocument("");
    var element = doc.createElement('div');

    function getText(str) {
        element.innerHTML = str;
        str = element.textContent;
        element.textContent = '';
        return str;
    }

    function decodeHTMLEntities(str) {
        if (str && typeof str === 'string') {
            var x = getText(str);
            while (str !== x) {
                str = x;
                x = getText(x);
            }
            return x;
        }
    }
    return decodeHTMLEntities;
})();
```

With the modified formatter, 

```js
rivets.formatters.htmlEntity = {
    read: function(string) {
        return decodeEntities(string);
    }
};
```

_source: http://stackoverflow.com/a/27385169/4092449_
