### ISSUE TITLE
Update/Better Documentation

### ISSUE THREAD

**Issue by robert-hoffmann** [mikeric/rivets#643]
Hi, really like the minimalism of rivets, but the lack of really in depth documentation is pushing me towards vuejs right now.

For example i had some problems getting a model to update properly ..after hours of searching i came across https://github.com/mikeric/rivets/issues/131#issuecomment-14826623 and was able to solve the issue with ``rview.update({todos: c2})`` ... which isn't even documented.

Please spend more time on the docs, rivets deserves it ...php, jquery, and others didnt take off because they where flexible ..but because they had rock solid and easy to understand docs, with lots of examples ;-)

Thanks !

**Comment by jccazeaux** [comment]
Doc was updated on github but not pushed in the site www.rivetsjs.com.
@Duder-onomy @Leeds-eBooks do you have the rights to update the site http://www.rivetsjs.com with the new doc?

I'm also updating the changelog. PR will follow

**Comment by Leeds-eBooks** [comment]
I don't know anything about the hosting of rivetsjs.com, it's `gh-pages` but I don't know how it's generated. Do you know already, to save me trying to work it out again?

**Comment by jccazeaux** [comment]
No I have no idea. I hoped you had the access as you have access to this repo

**Comment by Duder-onomy** [comment]
@jccazeaux Gh-pages works through a `gh-pages` orphan branch: [Rivets has this one](https://github.com/mikeric/rivets/tree/gh-pages)

If you make your commits there, I am pretty sure they will show up on the website.

(thanks for making those changes BTW, totally radical of you.)

**Comment by jccazeaux** [comment]
ok i'll send the PR on this branch. Thanks
