### ISSUE TITLE
Some bugs have been fixed. Time for a 0.9.2?

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#654]
Hi

There has been several bad issues detected. Some are fixed with PR.
### Issues

- [x] #644 

- [x] #650 

- [x] #649 

- [x] #658

### Doc update 

- [x] Details on computed properties (#658)

- [x] Download link update

@Leeds-eBooks 
@Duder-onomy 
Is it time for a `0.9.2`?

**Comment by Leeds-eBooks** [comment]
Definitely! #652 is fixed now too right?

**Comment by jccazeaux** [comment]
Yes, wrong issue, i meant 649.

**Comment by henkmollema** [comment]
What's the timeframe for this build? I'm hitting the bug in #650.

**Comment by Leeds-eBooks** [comment]
Very soon! Today, I hope.

**Comment by henkmollema** [comment]
Great! :smile:

**Comment by Leeds-eBooks** [comment]
Ok @jccazeaux I think I'm ready to publish `0.9.2`. You happy for me to go ahead?

**Comment by jccazeaux** [comment]
Yes !
I'll work on doc ASAP. Let's not reproduce the lag we had in 0.9.0

**Comment by Leeds-eBooks** [comment]
Great, once docs are merged I'll release.

**Comment by jccazeaux** [comment]
I sent the PR on branch `gh-pages`. Is it necessary to keep docs synced on master **and** `gh-pages`?

**Comment by Leeds-eBooks** [comment]
I don't think so, I think it just needs to be on `gh-pages`. But there may be a good reason that it is on both branches that I don't know about.

**Comment by jccazeaux** [comment]
I just found the `doc.sh` shell on master. This shell seems to automatically update `gh-pages` with current docs on `master`. For next update i'll use it !

**Comment by agmonks** [comment]
Maybe the Contributing section in the readme should be updated with how to update documents?

**Comment by jccazeaux** [comment]
Yes, first we must try it to be certain of how it works.

**Comment by Leeds-eBooks** [comment]
Ok I'm going to publish the release ASAP.

**Comment by Leeds-eBooks** [comment]
Done! @henkmollema you should be good to go.

**Comment by henkmollema** [comment]
Great, thanks! I'll try it out.

**Comment by agmonks** [comment]
@Leeds-eBooks looks live you have checked in the es6 build on master (in dist)?

**Comment by Leeds-eBooks** [comment]
@agmonks Ah balls, so I have. Stupid mistake. I will push `0.9.3` without it.

**Comment by Leeds-eBooks** [comment]
`0.9.3` published
