### ISSUE TITLE
Object.observe Deprecated

### ISSUE THREAD

**Issue by agmonks** [mikeric/rivets#657]
Object.observe has been deprecated (https://esdiscuss.org/topic/an-update-on-object-observe). the section in the guide needs amending ("The built-in adapter" http://rivetsjs.com/docs/guide/)

Maybe rivets should use Proxy's going forward to observe changes:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
http://caniuse.com/#search=Proxy

**Comment by Leeds-eBooks** [comment]
Nice idea regarding Proxies. This would allow us to observe getters as in #590.

Feel like submitting a PR to the `gh-pages` branch? 😛

**Comment by agmonks** [comment]
done in #659
