### ISSUE TITLE
Reminder for ES6 branch reports

### ISSUE THREAD

**Issue by jccazeaux** [mikeric/rivets#661]
We need to report code for the issues

- [x] #624 (#626)

- [x] #644 

- [x] #650 

- [x] #649 (#656)

- [x] #658

- [x] #619

**Comment by jccazeaux** [comment]
Closed to avoid pollution in open issues ;)

**Comment by Leeds-eBooks** [comment]
Great plan. Can I reopen? Want to keep this in mind.

**Comment by Leeds-eBooks** [comment]
@jccazeaux What do we need to do regarding https://github.com/mikeric/rivets/issues/658?

**Comment by jccazeaux** [comment]
Actually nothing, i listed the issues in 0.9.2 without analysis. I check it 😉

**Comment by Namek** [comment]
hey @jccazeaux - both #644 and #650 seem to be done

also #619 @Leeds-eBooks ?

**Comment by Namek** [comment]
also found #574 signatured as ES6

**Comment by Leeds-eBooks** [comment]
@Namek thanks – I have a very bad memory, got links for the es6 PRs that fix these issues?

**Comment by Namek** [comment]
heh, I was more asking than telling

**Comment by jccazeaux** [comment]
@Namek No they are not done. I just looked at the ES6 branch, the bugs are still there. To be sure we must report the tests first. I will do it when i have some time

**Comment by Leeds-eBooks** [comment]
@jccazeaux that would be brilliant, thanks!

**Comment by jccazeaux** [comment]
@Leeds-eBooks  it took more time than I expected but it's done !

**Comment by Leeds-eBooks** [comment]
@jccazeaux Great work, thanks!
