### ISSUE TITLE
Conditional Logic

### ISSUE THREAD

**Issue by wayneashleyberry** [mikeric/rivets#67]
It's me again :)

I'm new to data binding but i've been checking out knockout as well.

is it possible to do conditional logic with rivets?

something like this

``` html
<div class="post">
    <div data-if="post.type = foo">
        <h2>Foo</h2>
        <span>foo stuff</span>
    </div>
    <div data-if="post.type = bar">
        <h2>Bar</h2>
        <span>bar stuff</span>
    </div>
</div>
```

**Comment by jonathanwkelly** [comment]
For those looking at this working with the current codebase (as I was) : 

```
rivets.formatters.eq = function(value, checkAgainst)
{
  return (value == checkAgainst);
}

<div rv-show="post.someVal | eq 'foo'">show me if post.someVal is 'foo'; hide otherwise</div>
<div rv-show="post.someVal | eq 'bar'">show me if post.someVal if 'bar'; hide otherwise</div>
```

**Comment by thiagof** [comment]
Yeah, formatters seem to be the way to go.

Another cool way to have conditional logic is by piping parameters into a method.

    rv-class-pipe="'param' | functions.mymethod"

**Comment by vitmalina** [comment]
I have discovered that in JS, you can use "=", ">=", "<=", as method names. Then you can implement formatters in the following way:

```js
rivets.formatters['='] = function (value, arg) {
  return value == arg;
}

rivets.formatters['>'] = function (value, arg) {
  return value > arg;
}

rivets.formatters['>='] = function (value, arg) {
  return value >= arg;
}

rivets.formatters['<'] = function (value, arg) {
  return value < arg;
}

rivets.formatters['<='] = function (value, arg) {
  return value <= arg;
}
```

Then, when using it, it seems to make syntax cleaner:

```js
<ul>
	<li value="1" rv-class-selected="step | = 1" rv-on-click="setStep">Step 1</li>
	<li value="2" rv-class-selected="step | = 2" rv-on-click="setStep">Step 2</li>
	<li value="3" rv-class-selected="step | = 3" rv-on-click="setStep">Step 3</li>
	<li value="4" rv-class-selected="step | = 4" rv-on-click="setStep">Step 4</li>
</ul>
```
I cannot think of any negative effect so far, and I do like that it looks clean. The only thing I found is that there must be a space between "=" and "1" in "step | = 1"

**Comment by benliebert** [comment]
That is awesome. Nice one.

**Comment by sairfan1** [comment]
Hi, I want to apply logical operators, I want if Passed and Checked both are true then show.

<li rv-if="listing:Passed & listing:Checked">Show</li>

**Comment by Duder-onomy** [comment]
@sairfan1 Yes, logical operators are totally possible.

Here is a fiddle demonstrating your question: https://jsfiddle.net/yooqqxes/

The main idea is: 
1. make a formatter called and:

```javascript
rivets.formatters.and = function(comparee, comparator) {
    return comparee && comparator;
};
```

2. use it in your html like: 
```html
<div rv-if='listing.Passed | and listing.Checked'>
   Yeah, both are true. 
</div>
```

Leme know if that helps.

**Comment by sairfan1** [comment]
Thanks, I'm quite new to Rivets.js, can you please help how and where should i specify/declare formatter.

**Comment by calebroseland** [comment]
This is a bit old, but maybe someone will find it useful.

I made a simple 'or' formatter. I use it for checking multiple Booleans. There might be a better way to do this, but this is what worked for me. You can change the comparator to suite your specificity needs.

``` 
rivets.formatters["or"] = function () {
    var i = arguments.length;
    while (i--) if (typeof arguments[i] !== "undefined") return arguments[i];
    return false;
};
```
---
```
<div rv-if="item.foo | or item.bar, item.foobar"></div>

**Comment by lindseybradford** [comment]
Hi there, 

Just chiming in here (super helpful info above for sure! thanks!): is there a clean way to evaluate whether a condition is *not* true using rv templating. For example, here's what isn't working for me but conveys the goal:

```
<!-- show only when variant isn't Default -->
<div rv-show="item.variant_options.0 | != 'Default Title'">
  <div rv-text="item.variant_options.0"></div> 
</div>
```

Thanks in advance!
L

**Comment by Duder-onomy** [comment]
Hi L. 

Specifically to your example, there is an `rv-hide` binder which works the opposite of `rv-show` you could use to negate. There is also corresponding `rv-if` and `rv-unless` binders.  The diff between these 2 is that the show just makes the element `display:none` the if binder will remove the item from the dom. 


You can also chain formatters to accomplish something like what you are saying. 

Here is an example of a `not` formatter, this will negate anything sent into it. https://jsfiddle.net/cs4jug1L/

```html
<div rv-if='listing.Passed | and listing.Checked | not'>
        One is not checked.
</div>
```

Should give you some inspiration.

**Comment by khanSufiyan** [comment]
Hi There

I am using rv-if with custom formatter in a div

<div rv-show =" diamond.attributes.propertiesMap.fmx_inscription_number | or diamond.attributes.propertiesMap.lds_certificate_number" >

here is my formatter

rivets.formatters.or = function(comparee, comparator) {
  console.log("comparator",comparator);
    if (comparee == undefined && comparator == undefined){
      return false;
    }else{
      return comparee  || comparator;
    }
};

when i console it all i get is "diamond.attributes.propertiesMap.lds_certificate_number" insted of its actual value 
what am i missing over here?? Thanks in advance.

**Comment by Duder-onomy** [comment]
@khanSufiyan Here is a working fiddle demonstrating what I think you were trying to do. 

It has an element using the `rv-show` that is piping 2 diff values through a `or` formatter.

https://jsfiddle.net/Vornagreg/vrmrLzzq/

Can you fork and modify it to demonstrate your issue? 

(side note) If you are using backbone models...because I see the attributes property accessor, you will need to use a custom adapter to make sure rivets knows about changes correctly.

**Comment by khanSufiyan** [comment]
@Duder-onomy Thanks for the timely  reply.I saw that you used boolean value for checking the condition.All i want to do is pass a non boolean value and check weather it exists or not

**Comment by Duder-onomy** [comment]
@khanSufiyan Just trying help. 

Does this demonstrate what you wanted? 
https://jsfiddle.net/Vornagreg/sk11ngwm/

If you use the `!!` operator in front of a property, it will coerce it to a boolean. So, the `comparator` being a string, can be coerced with `!!`.

**Comment by khanSufiyan** [comment]
Hi I mentioned my problem in the comment in the below link hope  i am able to explain my problem this time
https://jsfiddle.net/tLLx5cad/

**Comment by Duder-onomy** [comment]
I am definitely confused now. lol. Isnt this what you wanted?

![image](https://cloud.githubusercontent.com/assets/1612785/17901731/99b5a30c-6919-11e6-9173-25dd293131d9.png)


OR, 
Do you want the value of the `diamond.attributes.propertiesMap.lds_certificate_number` to be inside the div?

**Comment by khanSufiyan** [comment]
yaa as you are getting "Hooraa" all i am getting in  the console is diamond.attributes.propertiesMap.lds_certificate_number

**Comment by Duder-onomy** [comment]
@khanSufiyan 

That is odd, I understand now. You are seeing the 'keypath' printed instead of the value. 

That is very very odd. 
To help me debug this:

* Can you try and make a fiddle where it does not work?
* Can you tell me what version of Rivets your using?
* Can you show me your init script, or, paste the code that is calling `rivets.bind`?
* Can you show me your exact formatter definition? 
* Can you show me the exact html that is binding and using the formatter?
* Can you show me the state of the model that is bound?
* Can you show me any custom adapters you are using?

This will be tough to help you as if this is true, it is a pretty massive issue.  I am willing to bet it is just  a implementation problem as no one else is having this issue right now.

**Comment by khanSufiyan** [comment]
@Duder-onomy I really appreciate the help that you offered.I will try to get the issue fixed at my end.As all your fiddles are working fine and I also think that it is an  implementation issue.I will come back if I am unable to solve it.Thanks for you time and help.

**Comment by khanSufiyan** [comment]
Hi @Duder-onomy I was able to solve that issue I was using an out date version.Update the version to the latest and every thing is working fine.Thanks for your help mate.

**Comment by mikepuerto** [comment]
@khanSufiyan I can't believe that code was resurrected. It was probably 5 years old. lol....
