### ISSUE TITLE
Why is the currentTime property of html5 audio not observable?

### ISSUE THREAD

**Issue by goose2460** [mikeric/rivets#670]
It seems like it is just an integer value so I'm not sure why it can't be observed.

http://jsfiddle.net/jTh3v/322/

<img width="268" alt="screen shot 2016-08-18 at 9 36 54 am" src="https://cloud.githubusercontent.com/assets/2341305/17782234/6da1ad92-6527-11e6-9823-0459d3e9cd69.png">

**Comment by Duder-onomy** [comment]
Very interesting, never seen anyone try and reverse bind to the property of a media tag before. 

Anyhow, here is a working fiddle binding in the correct direction: http://jsfiddle.net/Vornagreg/0jzdquuL/1/

I am not sure if this is a bug, or if I can really answer 'WHY' it does not work. 

Rivets observes keypaths by wrapping properties in custom getters and setter. (see [sightglass](https://github.com/mikeric/sightglass))
I would start by diving into the keypath engine in sightglass and seeing if it can even wrap that kind of property in getters and setters.

Usually, in rivets, if you want to bind a value to a property on an element, you would make a binder to do it. Not try and bind directly to the element as your model (as done in your fiddle)

The `rv-checked` binder for example, will actually listen for changes on the element then update the model. 

Here is another [fiddle](http://jsfiddle.net/Vornagreg/aefg69xq/) with a `rv-currenttime` binder, this will listen for the 'ontimeupdate' event on the element and update the model:

http://jsfiddle.net/Vornagreg/aefg69xq/

The pertinant bits:
(pardon the bad indentation)
```javascript
rivets.binders.currenttime = {
    publishes : true,
    bind : function(el) {
	    this.publish = this.publish.bind(this);
	    el.addEventListener('timeupdate', this.publish);
    },
    unbind : function() {
             el.removeEventListener('timeupdate', this.publish);
    },
    routine : function(el, value) {
             // Called when the model changes first.
             el.currentTime = value;
    },
    getValue : function(el) {
       // Called when the 'publish' method of the binding is called. // Return the currentTime
       return el.currentTime;
    }
};
```

And the HTML:

```html
<audio rv-currenttime='view.model.currentTime'  id="audio" src="http://www.sousound.com/music/healing/healing_01.mp3" preload="auto"></audio>
```

**Comment by Duder-onomy** [comment]
@goose2460 Can you close this issue if this helps you or let us know if you have any other issues.

**Comment by goose2460** [comment]
Very helpful, thanks

**Comment by goose2460** [comment]
Hmm, I'm getting really bad performance (skips and stutters) when using your 2-way binding example.  On Chrome and Safari.  Can you reproduce?  I cab open a separate issue if so.

**Comment by Duder-onomy** [comment]
My gut says the handler which published the value to the model should be throttled as the `currenttime` event fires WAY too much.

Ill look into it now.

**Comment by goose2460** [comment]
Preventing event default worked for me.  Is there a more concise way to do it?

`
el.addEventListener('timeupdate', function(evt){
			evt.preventDefault();
			this.publish(evt);
		});
`

**Comment by blikblum** [comment]
When i comment `el.currentTime = value;` in routine method it works fine

**Comment by Duder-onomy** [comment]
Yeah, @blikblum i see that as well. I guess there is a loop going on, when the binder publishes, then it thinks that it is also being set.

**Comment by goose2460** [comment]
Got it. Thanks for the help guys, closing

**Comment by Duder-onomy** [comment]
But wait. I think there is an issue here. Why would the binding be running in a loop? 
If the binder is setting the value to the model, why would the model in turn be trying to set the value back to the currentTime. Causing an infinite loop of publish and routine.

**Comment by blikblum** [comment]
In the value bind there's a check in routine to see if value is equal before setting element property. In this case i think will not work because currenttime may be changed in the meantime.
A flag like isUpdating could work

**Comment by goose2460** [comment]
Ah, had to read up on 2-way binders to see what the issue is. So the routine is getting triggered by the observer when it should only be firing on a (non publish) model change.

**Comment by Duder-onomy** [comment]
@blikblum Good call. this line here: https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L93

Here is the proof http://jsfiddle.net/Vornagreg/2zkkbnbw/,
if i add this line to the routine, then i hear no more jitter:
```javascript
routine: function(el, value) {
  if(this.observer.value().toString() !== value.toString()) {
    el.currentTime = value;
  }
},
```

Should we do something to avoid this completely?

**Comment by goose2460** [comment]
I can't get model-to-view binding to work with that fix, somehow `this.observer.value()` is already equal to `value` when the check happens.

http://jsfiddle.net/2zkkbnbw/1/
