### ISSUE TITLE
How to use adapters

### ISSUE THREAD

**Issue by ericxin1982** [mikeric/rivets#680]
Hi,

I try to learn rivets, I found it is very powerful.
I used other mvvm, but rivets adapters this concept to me is very strange, and I confused.
Does someone be able to show me a simple example how to use, and what is the perfect scenario for this feature?

Thanks
Eric Xin

**Comment by Namek** [comment]
I assume you've seen description of the adapters on http://rivetsjs.com/docs/guide/

If you're playing only with simple JS Objects then built-in `.` (dot) adapter is enough for you. However, if you want to subscribe to changes on some other data that have some more complicated structure than simple Objects then you could register another adapter or completely overwrite existing one. The Guide mentions Backbone framework as an example, however personally I haven't had a use to custom adapter yet.

**Comment by ericxin1982** [comment]
I did.
So can I ask that further step?
user.address:city, what this string try to do?
Get user.address value, and then to get city value from correct address? That is the example for? Thanks

**Comment by Duder-onomy** [comment]
@ericxin1982 

To decompose the keypath `user.address:city` to the best of my ability in words. 

Access the user from the root bound object, the root path is configurable, by default it is a `.`. Access the `address` property from the `user` by using the `.` adapter. Access the `city` property from the `address` using a `:` adapter. 

The `:` property accessor signifies, get this property (really subscribe to it as well) from this other thing by using this specific adapter. This is useful if the `address` is not just a regular POJO.  For example, if address were a backbone model. Backbone models store the internal properties on a `attributes` object. If this `:` adapter were using backbone, you could get around it by doing `user.address.attributes.city` However, this will not work as you expect. 

The adapter is used to teach the rivets core library HOW to access and listen for changes on a keypath. If you look into the internals of (sightglass)[https://github.com/mikeric/sightglass] you will see that it is wrapping and observing the keypaths subscribed. 

Some cool use cases of custom adapters would be subscribing to a websocket directly (think firebase without all the google).  You could also make an adapter for local storage. You could make an adapter for really anything. 

Does this help?

**Comment by ericxin1982** [comment]
Thanks.
I should read through sightglass first. That is new concept to me.

**Comment by ericxin1982** [comment]
@Duder-onomy 
Please see the code below.
<head>
    <script type='text/javascript' src='rivets.bundled.min.js' charset='utf-8'></script>
</head>
<body>
        <div id="exc">
            <input rv-value="item.channel.A" rv-on-keypress="item.detect">
        </div>
        <script>
            channel = {
                A:'a'
            }
            item = {
                name:'Magneto',
                detect:function(event){
                    console.log(event.keyCode);
                },
                channel:channel
            }
            
            rivets.bind(document.getElementById('exc'),{item: item})
        </script>
    </body>

![image](https://cloud.githubusercontent.com/assets/9047436/18627000/0d506d2a-7e8b-11e6-971c-cb7c57885203.png)

If I am using this way, <input rv-value="item.channel:A" rv-on-keypress="item.detect"> the input element does not have anything, is it right?

Would you mind giving me a example, I can digest it better.

Thanks

**Comment by ericxin1982** [comment]
I understand now, close this issue.
