### ISSUE TITLE
formater bi-directional, how?

### ISSUE THREAD

**Issue by ericxin1982** [mikeric/rivets#683]
Hi All,

As what I get learned about formater is single way, from left to right through a "|" like pipeline,  rivets.js has bi-directional formater, what is that, how to use in which scenerio,  anyone can give me some example?

Thanks
Eric Xin

**Comment by Namek** [comment]
I think the docs already say enough about this -> http://rivetsjs.com/docs/guide/#formatters but:

Note that there is **input** which is already thing that could be bound two-way:
```
<input rv-value="item.price | currency">
```
A formatter will format the binding in the fly. Two-way formatter will format data going both ways - when model data is changed and passed to (in this case) input element and when input element is edited and data is passed to source model.
