### ISSUE TITLE
When using jQuery, Data values on enumerated elements don't update with collection changes (they do, but jQuery does not know about it)

### ISSUE THREAD

**Issue by mhanders** [mikeric/rivets#684]
If a collection is enumerated with `rv-each`, then data is set on each element via `rv-data-*`, removing elements from the lists messes up the associated data retrieved by `$.data`. 

This [JSFiddle](https://jsfiddle.net/ze3u0cj0/3/) illustrates a direct example. Click the `Log data` and `Pop user` buttons to see how the `data` set doesn't jive with the popping. 

It's not clear to me what would be causing the issue here. Can anyone advise if this is likely a problem with the rivets code or a greater issue?

**Comment by Duder-onomy** [comment]
I think I fixed it for you, can you confirm that this is the behavior you wanted?
https://jsfiddle.net/Vornagreg/64fx59gt/

The pertinent bits:
Updated you call to bind: 

```javascript
rivets.bind(document.getElementById('details'), { 
    model : {
        users: users, 
        killUser: killUser, 
        logData: logData} 
    });
```

Then access it in the DOM via `model.users` and `model.killUser` etc.

This issue crops up all the time. You will always want to wrap most everything you bind in an object.  
I cannot explain exactly why, but it happens all the time and almost always the solution is to wrap it in an object. 

@Leeds-eBooks Might be able to explain it better. 

Please close if this helps you. I don't believe this is a bug as we have been very consistent in saying that people should always wrap it.

**Comment by mhanders** [comment]
Thanks for proposing a solution. I'm not seeing the problem resolved in that example.

The issue is that information stored in `$.data` becomes inconsistent as the list is modified. In the fiddle you posted I'm still seeing that, after popping the first user off, `$('p[data-name="Second"]').data()` gives me an object with `name: "First"`, whereas one would expect it to yield `name: "Second"`. 

Do you see the issue I'm referring to?

**Comment by Namek** [comment]
@mhanders use built-in browser DOM inspector to debug this. 

`$('p[data-name="Second"]').data()` seems to be wrong because of caching stuff. See answer here: http://stackoverflow.com/questions/21588044/jquerys-data-attribute-does-not-update-when-element-data-changes

**Comment by Duder-onomy** [comment]
Yeah, Thanks for clarifying,  I see what you are saying now. 

Isnt that a problem with jquery though? 
Cause if you look at the DOM, the attribute is in fact updated:

![image](https://cloud.githubusercontent.com/assets/1612785/18926986/b748e372-856e-11e6-95ad-37400b3228f8.png)

**Comment by Duder-onomy** [comment]
Considering it is def a jQuery issue and not a rivets issue. As illustrated by @Namek 

@mhanders  Can you close this?

**Comment by mhanders** [comment]
Definitely. Thanks for pinning down!

**Comment by blikblum** [comment]
This is a know rivets issue.

In the each binder, when the collection is already rendered, it reuses the elements. See https://github.com/mikeric/rivets/blob/master/src/binders.coffee#L193

It uses pop method of iterated views and then remove its element (the last one). When shift or slice method is used in the observed array, the elements <> data order desync.

See this updated fiddle to demonstrate that theres no problem when using pop. Also instrumented to track the elements order
