### ISSUE TITLE
Component update

### ISSUE THREAD

**Issue by kojilab** [mikeric/rivets#691]
How can I pass a new data/attributes object to a component once it has been initialized using rivets.init ? I've tried .bind, .update on the return of the init method but nothing works.

Thanks

**Comment by Namek** [comment]
You should simply update the same object given to `bind()`. If I don't understand that then please cover your question with some code.

**Comment by kojilab** [comment]
This is an example

```
var data = {
  title: 'Some title'
};
var element = document.getElementById('component-container');
var currentComponent = rivets.init('some-component', element, data);

```
Then later I want to keep the currentComponent and just feed it new data. Not sure how I can do this aside from reinitializing a new one.

Thanks

**Comment by Namek** [comment]
`data.title = 'new Title'` should work

**Comment by a-koka** [comment]
+1

I also tried this and don't see the component getting a new value. I was hoping something similar to a `routine` but looks like my attributes aren't updating when the data actually updates.

**Comment by Namek** [comment]
it works, have a look: http://plnkr.co/edit/rGkAliZvMnJGj74Lf6qU

**Comment by a-koka** [comment]
This issue is in regards to `components`. I understand that data usually propagates to `binders` via a `routine` and that works very well. The example above does NOT demonstrate a `component` where the `attribute` changes value after `initialization` which is where my problem lies.

Thanks!

**Comment by Namek** [comment]
@a-koka yeah sorry, I understood that just after posting. I was in too much in hurry and still wanted to help.

I hope this is what you need:
http://plnkr.co/edit/gXNQuwXDuJHUHvYsppyh

```
<!DOCTYPE html>
<html>

  <head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rivets/0.9.4/rivets.bundled.min.js"></script>
  </head>

  <body>
    <div id="app">
      {myCmpData.title}
      <my-component data="myCmpData"></my-component>
    </div>
    
    <button id="btn-change-title">Change title</button>
    
    <template id="my-component-template">
      <div style="border:1px solid steelblue">
        The title: {data.title}
      </div>
    </template>
    
    <script type="text/javascript">
      (() => {
        let $id = id => document.querySelector('#'+id)
        
        rivets.components['my-component'] = {
          template: () => $id('my-component-template').innerHTML,
          initialize: (el, attrs) => {
            return { data: attrs.data }
          }
        }
        
        let scope = {
          myCmpData: {
            title: "some title"
          }
        }
        
        rivets.bind($id('app'), scope)

        $id('btn-change-title').addEventListener('click', () => {
          scope.myCmpData.title = "changed title"
        })
      })()
    </script>
  </body>

</html>
```

**Comment by a-koka** [comment]
You're right @Namek! I noticed an issue on my and and I was also using `0.8.1`. I have it working now on `0.9.4`. Thanks for your quick responses.

**Comment by kojilab** [comment]
Thanks for those good examples. Helped me a lot.
In my case I have a router library and a component for each page. If the user goes to a page/route that uses the same component, I want to keep that component and just update the model.

So I had to do something like this based on your examples:

```

    var currentComponentName, currentData;
    app.renderComponent = function(name, data, options) {        

        // if data is null, false or undefined, then create a 404
        if (!data || data === undefined) {
            name = 'not-found';
        }
        
        if (name != currentComponentName) {
            rivets.init(name, routeEl, data);
            currentComponentName = name;
            currentData = data;
        } else {
            _.each(data, function(v, k) {
                currentData[k] = v;
            });
        }
        
    };
```
