### ISSUE TITLE
Incorrect version

### ISSUE THREAD

**Issue by a-koka** [mikeric/rivets#693]
On `0.9.4`, all files under `dist` say `0.9.3` in their comments and except the bundled file, the other two files say `0.9.3` for their on the GitHub page as well. This is quite confusing. I am hoping that it is just an oversight and all files are actually `0.9.4`.

Would someone be able to confirm this?

Thank you!

**Comment by Namek** [comment]
By looking at commits on https://github.com/mikeric/rivets/commits/master `0.9.3` and `0.9.4` are exactly the same. That was probably some mistake during publish. @Leeds-eBooks 

Also changelog lacks of `0.9.3`:
https://github.com/mikeric/rivets/commit/012e3e16a6510d3c06cdff4e099644a5a38ab9cd

**Comment by Leeds-eBooks** [comment]
Ah this was totally my mistake. Yeah it was a publishing error, I thought I'd caught all the references to `0.9.3`. The correct version is `0.9.4`. Do you think it's worth me pushing a `0.9.5` to fix all of this?

**Comment by Namek** [comment]
Merge my latest PR and then release new ver :)
