### ISSUE TITLE
executeFunctions disallowing call

### ISSUE THREAD

**Issue by a-koka** [mikeric/rivets#696]
My app is set to use `executeFunctions` as we have 100s of functions written out using the old syntax. I'd love to use `call` so that parameters can be passed into functions but seems like `executeFunctions` disables the ability to use `call`.

I realize that this may be a bit of a corner case. Just wondering if there are any suggestions around this issue besides re-writing all the functions with a `call`.

Thank you!

**Comment by Namek** [comment]
Probably issue is too old and you choosed one of two paths.

Personally, I don't think this corner case would be worth implementing. It feels smelly. To me it doesn't sound to be that big change since it's easy to just add ` | call` everywhere.

**Comment by Leeds-eBooks** [comment]
Yeah I'm afraid `| call` _was_ our solution – it's one or the other. Closing.
