### ISSUE TITLE
Using rivets on cordova android.

### ISSUE THREAD

**Issue by fsvieira** [mikeric/rivets#703]
Hi, I am doing a application on cordova to run on android, I am using rivets.

I load the template successfully with jquery and than I bind the data with rivets but it doesn't show any data, on element inspect I can see that no data is set on elements.

What can I do to debug and solve this issue?
Thanks, great lib.

**Comment by Namek** [comment]
Can you verify your code works on desktop browser? Plunker?

**Comment by fsvieira** [comment]
Hi, 

It is working ok on the browser, but I made some more tests and the bug seems not to be on rivetjs, I made a basic test with a counter and it updates ok.

Sorry for the trouble, I will close the issue.
