### ISSUE TITLE
Event handling

### ISSUE THREAD

**Issue by toby1kenobi** [mikeric/rivets#706]
Rivets looks really useful, but I'm struggling with the documentation. If I use rv-each-* to output a list of items, and I want something in each to be click-able, is there are rivet-y way of hooking these up or should I just use jQuery or something?

I can see [here](http://rivetsjs.com/docs/guide/#usage-configuring) a reference to augmenting 'the event handler of the on-* binder', which sounds hopeful, that seems to be the only reference to it though.

**Comment by Leeds-eBooks** [comment]
Hi, sorry for the delay. This is exactly the kind of thing rivets is for. You simply use the `on-*` binder, as referenced [here](http://rivetsjs.com/docs/reference/#on-[event]). So your html might look like (where `items` is an array and `openItem` is a function):

```
<ul>
  <li rv-each-item="items" rv-on-click="openItem"></li>
</ul>
```

Does that help at all?

**Comment by toby1kenobi** [comment]
Thanks, that looks great - not sure how I'd missed it!

**Comment by Leeds-eBooks** [comment]
Cool, closing this, feel free to open another issue if you have any other problems!
