### ISSUE TITLE
component

### ISSUE THREAD

**Issue by ericxin1982** [mikeric/rivets#709]
Hi Team,

So just wondering whether there is a full example for component where I can learn?

Thanks
Eric Xin

**Comment by Namek** [comment]
Hi, does the Guide misguide you or just want to see a plunker?
http://rivetsjs.com/docs/guide/#components

**Comment by ericxin1982** [comment]
Hi, if there is an available jsfiddle would be great, I can have an online try. I am not sure plunker means.
And I do not know what it means as below:
return JST['todos/todo-item']






At 2017-03-07 22:47:42, "Namek" <notifications@github.com> wrote:


Hi, does the Guide misguide you or just want to see a plunker?
http://rivetsjs.com/docs/guide/#components

**Comment by Namek** [comment]
In the `JST` part you simply provide a template. This has to be a string containing HTML that uses normal rivets bindings etc. In my case it is:
```js
template: function() {
	return $id('member-list-template').innerHTML
},
```

and the template is injected into `<head>` part of website by PHP:
```
<script type="text/html" id="member-list-template">{{ View::make('club/member-list') }}</script>
```

**Comment by ericxin1982** [comment]
would you mind giving me the a whole picture, I am confused. @Namek

**Comment by ericxin1982** [comment]
Hi Namek,


Would you please give me these two html files, so I can have a better understanding.
I am too new to this part.


Thanks
Eric Xin






At 2017-03-07 23:05:44, "Namek" <notifications@github.com> wrote:


In the JST part you simply provide a template. This has to be a string containing HTML that uses normal rivets bindings etc. In my case it is:

template:function() {
	return$id('member-list-template').innerHTML
},

and the template is injected into <head> part of website by PHP:

<script type="text/html" id="member-list-template">{{ View::make('club/member-list') }}</script>

**Comment by Namek** [comment]
Hi, sorry fo taking so long. You may take inspiration from this article:
https://www.namekdev.net/2017/05/binding-with-rivets-js-details-and-tricks/

or this live example:
http://plnkr.co/edit/gXNQuwXDuJHUHvYsppyh?p=preview

the live example was already mentioned so you didn't dig well enough:
https://github.com/mikeric/rivets/issues/691

Please consider closing this issue.

**Comment by Leeds-eBooks** [comment]
Looks like @Namek has replied fully, please reopen if you need.
