### ISSUE TITLE
Is there any way to use WC3 valid attributes for rivets?

### ISSUE THREAD

**Issue by Andrinoid** [mikeric/rivets#718]
First of all, thank you guys for the wonderful framework.
Here is my issue. I'm get WC3 error for every rv- attribute I have on my page. Is there anyway to use valid attributes with rivets.

**Comment by Namek** [comment]
Maybe change the prefix from `rv` to `data-rv`? Search "prefix" in "Configuring" section on http://rivetsjs.com/docs/guide/

**Comment by Andrinoid** [comment]
Thank you. I had to use only data as prefix. I might be wrong but I think the hyphen is used as a logic separator in some binders so data-rv failed in some cases.  Below is the configuration that worked for me.
```
rivets.configure({
  // Attribute prefix in templates
  prefix: 'data',
})
```
then in my templates
`<div data-if="app.someValue">`
