### ISSUE TITLE
Improve data-value bindings on dynamic select elements

### ISSUE THREAD

**Issue by mcolyer** [mikeric/rivets#75]
This isn't really a bug but more a feature request

Example:

```
<select data-value="model.item" >
  <option data-each-item="model.items" data-text="item.name" data-value="item.name"></option>
</select>
```

If you bind a model to this it won't select the proper item in the select because it will attempt to set the value before the options exist. Right now I'm working around it by manually forcing the data-value binding to run again.

Any ideas of how to make it better?

**Comment by eimajenthat** [comment]
@andriijas and @smasala I think I figured out how to do it: http://jsfiddle.net/eimajenthat/94ca1xht/2/

Don't pay too much attention to the Chosen part, unless you're using Chosen too.

This seems to work for me.  But if anyone would like to comment about how I'm doing everything wrong, and there is an infinitely superior way to accomplish this, be my guest.
