### ISSUE TITLE
Ability to specify "fallback value"

### ISSUE THREAD

**Issue by chrismcv** [mikeric/rivets#93]
Just another quick thought.  WPF binding has a really useful feature for specifying Fallback value on a binding.  I was wondering if there might be a way to do this with the pipe type operator?

```
data-text="object.name | | Default Value"
```

**Comment by MarcFowler** [comment]
I know this is an old one, but I just came across it and actually, arguments are no longer broken up by spaces, right?

So actually the original you posted there @mikeric works great from what I can see:

```js
rivets.formatters.fallback = function(value, default) {
  return value || default
};
```

```html
<div rv-text="some.value | fallback 'No value specified'"></div>
```

(Working on v0.8.0)

**Comment by Leeds-eBooks** [comment]
@MarcFowler yep, because formatters now take literals, and you've put quotes around your argument, this would work as expected.

**Comment by MarcFowler** [comment]
Yep, that's awesome. This was the first result in Google so I thought I should post in case someone else found it the same way I did!
